import {describe,it,expect} from 'vitest';
import {adfProjection,markdownProjection,toAdf,compareResource,captureBase,validateBinding,validateBindings,splitFrontmatter} from '../src';
import type {LocalResource,RemoteResource} from '../src';
const local:LocalResource={path:'docs/story.md',revision:'a'.repeat(64),title:'Story',text:'Hello **world**.\n'};
function remote(text='Hello **world**.'):RemoteResource{return {provider:'jira',deployment:'cloud',instance:'https://team.atlassian.net',id:'123',key:'TEAM-1',url:'https://team.atlassian.net/browse/TEAM-1',scopeId:'10',title:'Story',version:'2026-09-27T00:00:00Z',observedAt:'2026-09-27T00:00:00Z',fields:{title:'Story',description:text,status:'Ready'},content:markdownProjection(text),representation:'adf',draft:'absent',provenance:{api:'/rest/api/3/issue/123',profile:'jira-cloud-rest-v3'}};}
describe('loss-aware browser-safe content',()=>{
  it.each(['Hello **world** and *emphasis* with ~~strike~~ and `code`.','# Header\n\nParagraph with [link](https://example.com/a).','- One\n- Two\n\n1. First\n2. Second','> Quoted text\n\n---','```ts\nconst n = 1;\n```','| Name | State |\n| --- | --- |\n| A | Ready |'])('roundtrips supported Markdown through ADF: %s',text=>{
    const projection=markdownProjection(text);expect(projection.complete).toBe(true);const roundtrip=adfProjection(toAdf(projection));expect(roundtrip.complete).toBe(true);expect(roundtrip.nodes).toEqual(projection.nodes);expect(markdownProjection(roundtrip.markdown).nodes).toEqual(projection.nodes);
  });
  it('retains frontmatter and BOM separately from managed body',()=>{const text='\uFEFF---\r\nstatus: ready\r\n---\r\nHello';expect(splitFrontmatter(text)).toEqual({prefix:'\uFEFF---\r\nstatus: ready\r\n---\r\n',body:'Hello'});expect(markdownProjection(text).nodes).toEqual(markdownProjection('Hello').nodes);});
  it.each(['<div>HTML</div>','![image](local.png)','- [x] Done','[ref][x]\n\n[x]: https://example.com','| A |\n| :---: |\n| B |'])('marks unsupported Markdown as partial: %s',text=>{expect(markdownProjection(text).complete).toBe(false);expect(()=>toAdf(markdownProjection(text))).toThrow();});
  it.each(['mention','mediaSingle','extension','inlineCard','bodiedExtension'])('marks ADF %s as opaque and partial',type=>{const p=adfProjection({version:1,type:'doc',content:[{type,attrs:{id:'private'}}]});expect(p.complete).toBe(false);expect(p.unsupported).toContain(type);});
  it('rejects unsafe link semantics and unknown attributes',()=>{expect(adfProjection({version:1,type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'x',marks:[{type:'link',attrs:{href:'javascript:alert(1)'}}]}]}]}).complete).toBe(false);expect(adfProjection({version:1,type:'doc',content:[{type:'tableCell',attrs:{rowspan:2}}]}).complete).toBe(false);});
});
describe('field-scoped three-way comparisons',()=>{
  it('compares equivalent markup without changing a file',()=>expect(compareResource(local,remote('Hello __world__.'),['description']).state).toBe('equal'));
  it('separates a proven document title from body, preserving unmatched headings and entity text',()=>{const r={...remote('Imported body'),provider:'confluence' as const,fields:{title:'Remote title',body:'Imported body'}};const doc={...local,title:'Local title',text:'---\ntitle: Local title\n---\n# Local title\n\nImported body'};expect(compareResource(doc,r,['body']).state).toBe('equal');expect(compareResource({...doc,text:'# Different heading\n\nImported body'},r,['body']).state).toBe('no-base');expect(compareResource({...doc,entityId:'story-1'},r,['body']).state).toBe('no-base');expect(compareResource(doc,r,['body'],captureBase(doc,r)).state).toBe('equal');});
  it('does not infer a base when values differ',()=>expect(compareResource(local,remote('Remote change'),['description']).state).toBe('no-base'));
  it('distinguishes local, remote, both and convergent edits',()=>{const original=remote(),base=captureBase(local,original),changed={...local,text:'New text'};expect(compareResource(changed,original,['description'],base).state).toBe('local-changes');expect(compareResource(local,remote('Elsewhere'),['description'],base).state).toBe('remote-changes');expect(compareResource(changed,remote('Elsewhere'),['description'],base).state).toBe('both-changed');expect(compareResource(changed,remote('New text'),['description'],base).state).toBe('convergent');});
  it('does not report unsupported body content as equality',()=>{const r=remote('![image](image.png)');expect(compareResource({...local,text:'![image](image.png)'},r,['description']).state).toBe('partial');expect(compareResource(local,r,['title']).state).toBe('equal');});
  it('binds bases to immutable instance and resource and normalizer',()=>{const base=captureBase(local,remote());expect(()=>compareResource(local,{...remote(),id:'124'},['title'],base)).toThrow();expect(()=>compareResource(local,remote(),['title'],{...base,normalizerVersion:2 as 1})).toThrow();});
});
describe('versioned project mapping metadata',()=>{
  const binding={schemaVersion:1,normalizerVersion:1,id:'link1',projectId:'project',provider:'jira',deployment:'cloud',instance:'https://team.atlassian.net',resourceId:'123',resourceUrl:'https://team.atlassian.net/browse/TEAM-1',scopeId:'10',local:{path:'docs/story.md',entityId:'1-1'},fields:['title','description'],policy:'review-both-directions'};
  it('accepts explicit existing-resource binding',()=>expect(validateBinding(binding).resourceId).toBe('123'));
  it('rejects unsafe paths, cross-instance URLs and credentials',()=>{expect(()=>validateBinding({...binding,local:{path:'../secrets'}})).toThrow();expect(()=>validateBinding({...binding,resourceUrl:'https://other.atlassian.net/page'})).toThrow();expect(()=>validateBinding({...binding,token:'secret'})).toThrow();});
  it('rejects duplicate link metadata',()=>expect(()=>validateBindings([binding,binding])).toThrow('Duplicate'));
});
