import {test,expect,installDiskPicker} from './filesystem';
import {serve} from '@hono/node-server';
import type {Hono} from 'hono';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createAtlassianApp} from '../../apps/atlassian-connector/src/service';
import type {ProviderAdapter} from '../../apps/atlassian-connector/src/adapters';
import {markdownProjection} from '../../packages/integrations/src/index';
import type {RemoteResource} from '../../packages/integrations/src/index';

// Real local HTTP service and comparison pipeline; only the account adapter is
// synthetic. These tests do not claim access to a live Atlassian tenant.
async function mockAtlassian(provider:'jira'|'confluence'='confluence') {
 const token=`e2e-only-${provider}-launcher-capability-123456789`;let writes=0,app:Hono;
 const isJira=provider==='jira',body=isJira?'Recordatorio importado desde Jira\n\nSin envío externo\n':'Contenido remoto inicial.\n',title=isJira?'Recordatorio remoto protegido':'Página remota de riego';
 const remote:RemoteResource={provider,deployment:'cloud',instance:'https://bmad-e2e.example.test',id:'101',...(isJira?{key:'HUERTO-17'}:{}),url:isJira?'https://bmad-e2e.example.test/browse/HUERTO-17':'https://bmad-e2e.example.test/wiki/pages/101',scopeId:'7',scopeName:'Huerto',title,version:'1',observedAt:new Date().toISOString(),fields:isJira?{title,description:body,status:'Open'}:{title,body},content:markdownProjection(body),representation:'adf',draft:isJira?'absent':'unknown',provenance:{api:'mock',profile:`mock-${provider}`}};
 const adapter:ProviderAdapter={instance:remote.instance,capabilities:{provider,deployment:'cloud',profile:`mock-${provider}-safe-read`,read:true,search:true,compare:true,import:true,export:true,remoteUpdate:false,fields:isJira?['title','description','status']:['title','body'],representations:['adf'],concurrency:isJira?'none':'versioned-with-draft-risk',blockedReasons:[isJira?'La cuenta simulada no garantiza una precondición atómica.':'La cuenta simulada no garantiza preservar borradores remotos.'],liveVerified:false},identity:async()=>({id:'account-e2e',displayName:'Cuenta simulada E2E'}),scopes:async()=>({items:[{id:'7',name:'Huerto',key:'HUERTO'}],complete:true,warnings:[]}),search:async()=>({items:[{id:remote.id,key:remote.key,title:remote.title,url:remote.url,scopeId:remote.scopeId,version:remote.version}],complete:true,warnings:[]}),read:async()=>structuredClone(remote),history:async()=>({items:[{id:'1',version:'1',summary:isJira?'Incidencia creada en fixture':'Página creada en fixture'}],complete:true,warnings:[]}),candidate:(request,item)=>({title:request.direction==='import'?item.title:request.local.title,text:request.direction==='import'?item.content.markdown:request.local.text,status:request.direction==='import'?item.fields.status:request.local.status}),apply:async()=>{writes++;throw new Error('The blocked mock adapter must never be called');}};
 let ready!:(port:number)=>void;const listening=new Promise<number>(resolve=>{ready=resolve;});const server=serve({fetch:request=>app.fetch(request),hostname:'127.0.0.1',port:0},info=>ready(info.port));const port=await listening;app=await createAtlassianApp({adapter,origin:'http://127.0.0.1:5173',port,launcherToken:token,journalDirectory:await mkdtemp(join(tmpdir(),'bmad-atlassian-ui-'))});
 return {token,port,remote,get writes(){return writes;},update(body:string){remote.version=String(Number(remote.version)+1);remote.fields[isJira?'description':'body']=body;remote.content=markdownProjection(body);remote.observedAt=new Date().toISOString();},close:()=>new Promise<void>((resolve,reject)=>{server.close(error=>error?reject(error):resolve());if('closeAllConnections' in server)server.closeAllConnections();})};
}

test('walks six verified steps, links, blocks unsafe publish and imports reviewed fields with stale checks',async({page,project},info)=>{
 const service=await mockAtlassian();try{
  const path=join(project,'docs/notas/reunion.md');const original='---\ntitle: Título local protegido\nstatus: draft\ncustom: preserve-me\n---\n# Título local protegido\n\nCuerpo original.\n';await writeFile(path,original);
  await page.goto('/');await page.getByRole('button',{name:'Elegir carpeta del proyecto'}).click();await page.getByRole('button',{name:'reunion.md',exact:true}).click();await page.getByRole('button',{name:'Activar Editor'}).click();await page.getByRole('button',{name:/Conexión con Confluence/}).click();await page.getByRole('button',{name:'Configurar conexión',exact:true}).click();await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.getByLabel('Dirección local del conector de Confluence').fill(`http://127.0.0.1:${service.port}`);await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.getByLabel('Cargar archivo de sesión de Confluence',{exact:true}).setInputFiles({name:'session.txt',mimeType:'text/plain',buffer:Buffer.from(service.token)});await page.getByRole('button',{name:'Autorizar conexión con Confluence',exact:true}).click();await expect(page.getByText('Cuenta simulada E2E',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Atrás',exact:true}).click();await page.getByRole('button',{name:'Continuar con conexión autorizada'}).click();await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.getByRole('button',{name:'Comprobar acceso y recurso'}).click();await expect(page.getByText('Completa para el ámbito consultado',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.getByRole('button',{name:'Guardar conexión',exact:true}).click();await expect(page.getByText('Conectado para consultar',{exact:true})).toBeVisible();
  await page.getByRole('combobox',{name:'Elemento local',exact:true}).selectOption('docs/notas/reunion.md');await page.getByRole('button',{name:'Buscar candidatos'}).click();await page.getByRole('button',{name:'101 · Página remota de riego'}).click();await page.getByRole('button',{name:'Confirmar vínculo'}).click();await expect(page.getByText('Vínculo guardado. No se ha publicado ni importado contenido.')).toBeVisible();await page.getByRole('checkbox',{name:'Título',exact:true}).uncheck();await page.getByRole('button',{name:'Comparar campos'}).click();await expect(page.getByRole('heading',{name:'Sin base común',exact:true})).toBeVisible();await page.getByRole('button',{name:'Revisar publicación'}).click();let dialog=page.getByRole('dialog');await expect(dialog).toContainText('La cuenta simulada no garantiza preservar borradores remotos.');await expect(dialog.getByRole('button',{name:'Confirmar publicación'})).toBeDisabled();await dialog.getByRole('button',{name:'Volver a comparar'}).click();
  await page.getByRole('combobox',{name:'Dirección',exact:true}).selectOption('import');await page.getByRole('button',{name:'Comparar campos'}).click();await page.getByRole('button',{name:'Revisar importación'}).click();dialog=page.getByRole('dialog');await expect(dialog).toContainText('Archivos locales que cambiarán');await expect(dialog).toContainText('custom: preserve-me');await expect(dialog.getByRole('button',{name:'Confirmar importación'})).toBeEnabled();service.update('Contenido remoto actualizado tras la revisión.\n');await dialog.getByRole('button',{name:'Confirmar importación'}).click();await expect(page.getByText('El recurso remoto cambió después de revisar. Compara de nuevo antes de importar.')).toBeVisible();expect(await readFile(path,'utf8')).toBe(original);
  await page.getByRole('button',{name:'Comparar campos'}).click();await page.getByRole('button',{name:'Revisar importación'}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:'Confirmar importación'})).toBeEnabled();for(const width of [1440,1024,651,650,649,581,580,579,401,400,399,320]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Confluence review at ${width}px`).toBe(true);expect(await dialog.evaluate(element=>element.scrollWidth<=element.clientWidth),`Confluence dialog at ${width}px`).toBe(true);}await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:info.outputPath('confluence-reviewed-import.png'),fullPage:false});await dialog.getByRole('button',{name:'Confirmar importación'}).click();await expect(page.getByText('Importación guardada localmente y verificada. Git no se ha modificado.')).toBeVisible();const saved=await readFile(path,'utf8');expect(saved).toContain('custom: preserve-me');expect(saved).toContain('status: draft');expect(saved).toContain('# Título local protegido');expect(saved).toContain('Contenido remoto actualizado tras la revisión');expect(saved).not.toContain('Cuerpo original.');expect(service.writes).toBe(0);await page.getByRole('button',{name:'Documentos',exact:true}).click();await expect(page.getByText('Contenido remoto actualizado tras la revisión.',{exact:true})).toBeVisible();
  const metadata=await readFile(join(project,'.bmad-project-ui/integrations/confluence.json'),'utf8');expect(metadata).not.toContain(service.token);expect(metadata).not.toContain('Contenido remoto');expect(JSON.parse(metadata).bindings).toHaveLength(1);expect(await page.evaluate(()=>JSON.stringify(localStorage))).not.toContain(service.token);
  await page.getByRole('button',{name:/Conexión con Confluence/}).click();await page.getByRole('button',{name:/docs\/notas\/reunion.md/}).click();await page.getByRole('checkbox',{name:'Título',exact:true}).uncheck();service.update('Cambio remoto posterior a la base verificada.\n');await page.getByRole('button',{name:'Comparar campos'}).click();await expect(page.getByRole('heading',{name:'Cambios remotos',exact:true})).toBeVisible();await expect(page.getByText(/Base privada guardada en este navegador/)).toBeVisible();await page.getByRole('button',{name:'Revisar importación'}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:'Confirmar importación'})).toBeEnabled();const config=JSON.parse(metadata);config.connection.localRoot='docs/notas';await writeFile(join(project,'.bmad-project-ui/integrations/confluence.json'),JSON.stringify(config));await dialog.getByRole('button',{name:'Confirmar importación'}).click();await expect(page.getByText('La asociación o su ámbito cambiaron después de revisar. Compara de nuevo antes de aplicar.')).toBeVisible();expect(await readFile(path,'utf8')).toBe(saved);
  const reopened=await page.context().newPage();await installDiskPicker(reopened,project);await reopened.goto('/');await reopened.getByRole('button',{name:'Elegir carpeta del proyecto'}).click();await reopened.getByRole('button',{name:'Activar Editor'}).click();await reopened.getByRole('button',{name:/Conexión con Confluence/}).click();await reopened.getByRole('button',{name:'Configurar conexión',exact:true}).click();await reopened.getByRole('button',{name:'Siguiente',exact:true}).click();await reopened.getByLabel('Dirección local del conector de Confluence').fill(`http://127.0.0.1:${service.port}`);await reopened.getByRole('button',{name:'Siguiente',exact:true}).click();await reopened.getByLabel('Cargar archivo de sesión de Confluence',{exact:true}).setInputFiles({name:'session.txt',mimeType:'text/plain',buffer:Buffer.from(service.token)});await reopened.getByRole('button',{name:'Autorizar conexión con Confluence',exact:true}).click();await reopened.getByRole('button',{name:'Siguiente',exact:true}).click();await reopened.getByRole('button',{name:'Comprobar acceso y recurso'}).click();await expect(reopened.getByText('Completa para el ámbito consultado',{exact:true})).toBeVisible();await reopened.getByRole('button',{name:'Siguiente',exact:true}).click();await reopened.getByRole('button',{name:'Guardar conexión',exact:true}).click();await reopened.getByRole('button',{name:/docs\/notas\/reunion.md/}).click();await reopened.getByRole('checkbox',{name:'Título',exact:true}).uncheck();await reopened.getByRole('button',{name:'Comparar campos'}).click();await expect(reopened.getByRole('heading',{name:'Cambios remotos',exact:true})).toBeVisible();await expect(reopened.getByText(/Base privada guardada en este navegador/)).toBeVisible();await reopened.close();
 }finally{await service.close();}
});

test('links a Jira story and imports only its reviewed YAML description without changing sibling bytes or the remote',async({page,project})=>{
 const service=await mockAtlassian('jira');try{
  const container='_bmad-output/specs/spec-notificaciones/stories.yaml',path=join(project,container),original=await readFile(path,'utf8'),execution=join(project,'_bmad-output/specs/spec-notificaciones/stories/1-programar-recordatorio.md'),executionBefore=await readFile(execution,'utf8'),sprint=join(project,'_bmad-output/implementation-artifacts/sprint-status.yaml'),sprintBefore=await readFile(sprint,'utf8'),remoteBefore=structuredClone(service.remote);
  await page.goto('/');await page.getByRole('button',{name:'Elegir carpeta del proyecto'}).click();await page.getByRole('button',{name:'Activar Editor'}).click();await page.getByRole('button',{name:/Conexión con Jira/}).click();await page.getByRole('button',{name:'Configurar conexión',exact:true}).click();await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.getByLabel('Dirección local del conector de Jira').fill(`http://127.0.0.1:${service.port}`);await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.getByLabel('Cargar archivo de sesión de Jira',{exact:true}).setInputFiles({name:'session.txt',mimeType:'text/plain',buffer:Buffer.from(service.token)});await page.getByRole('button',{name:'Autorizar conexión con Jira',exact:true}).click();await expect(page.getByText('Cuenta simulada E2E',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.getByRole('button',{name:'Comprobar acceso y recurso'}).click();await expect(page.getByText('Completa para el ámbito consultado',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.getByRole('button',{name:'Guardar conexión',exact:true}).click();await expect(page.getByText('Conectado para consultar',{exact:true})).toBeVisible();
  await page.getByRole('combobox',{name:'Elemento local',exact:true}).selectOption({label:'2 · Mostrar recordatorio'});await page.getByRole('button',{name:'Buscar candidatos'}).click();await page.getByRole('button',{name:'HUERTO-17 · Recordatorio remoto protegido'}).click();await page.getByRole('button',{name:'Confirmar vínculo'}).click();await expect(page.getByText('Vínculo guardado. No se ha publicado ni importado contenido.')).toBeVisible();await page.getByRole('checkbox',{name:'Título',exact:true}).uncheck();await expect(page.getByRole('checkbox',{name:'Estado',exact:true})).not.toBeChecked();await page.getByRole('combobox',{name:'Dirección',exact:true}).selectOption('import');await page.getByRole('button',{name:'Comparar campos'}).click();await expect(page.getByRole('heading',{name:'Sin base común',exact:true})).toBeVisible();await page.getByRole('button',{name:'Revisar importación'}).click();const dialog=page.getByRole('dialog');await expect(dialog).toContainText('Archivos locales que cambiarán');await expect(dialog).toContainText(container);await expect(dialog).toContainText('Programar recordatorio');await expect(dialog).toContainText('done_checkpoint: true');await expect(dialog.getByRole('button',{name:'Confirmar importación'})).toBeEnabled();expect(await readFile(path,'utf8')).toBe(original);await dialog.getByRole('button',{name:'Confirmar importación'}).click();await expect(page.getByText('Importación guardada localmente y verificada. Git no se ha modificado.')).toBeVisible();
  const expected=original.replace('Mostrar un aviso local sin envío externo.',JSON.stringify(service.remote.content.markdown));expect(await readFile(path,'utf8')).toBe(expected);expect(await readFile(execution,'utf8')).toBe(executionBefore);expect(await readFile(sprint,'utf8')).toBe(sprintBefore);expect(service.writes).toBe(0);expect(service.remote).toEqual(remoteBefore);const rawMetadata=await readFile(join(project,'.bmad-project-ui/integrations/jira.json'),'utf8'),metadata=JSON.parse(rawMetadata);expect(metadata.bindings).toHaveLength(1);expect(metadata.bindings[0].local.path).toBe(container);expect(metadata.bindings[0].local.entityId).toContain('#stories:2:');expect(rawMetadata).not.toContain(service.token);expect(rawMetadata).not.toContain('Recordatorio importado desde Jira');
 }finally{await service.close();}
});
