import {test,expect} from './filesystem';
import {createHash,randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
const hash=(text:string)=>createHash('sha256').update(text).digest('hex');

test('reviews and exports private copies before restoring an interrupted multi-file save',async({page,project})=>{
 const paths=['docs/notas/reunion.md','docs/manual/riego.md'];const copies=await Promise.all(paths.map(async path=>{const before=await readFile(join(project,path),'utf8');return {path,before,after:before+'\nContenido de un guardado interrumpido.\n'};}));const id=randomUUID();const journal={schemaVersion:1,id,createdAt:new Date().toISOString(),entries:copies.map(copy=>({path:copy.path,before:hash(copy.before),after:hash(copy.after)}))};await writeFile(join(project,paths[0]),copies[0].after);await mkdir(join(project,'.bmad-project-ui/local'),{recursive:true});await writeFile(join(project,'.bmad-project-ui/local/write-recovery.json'),JSON.stringify(journal));
 await page.goto('/');await page.evaluate(async({id,copies})=>{const directory=await(await navigator.storage.getDirectory()).getDirectoryHandle('bmad-project-ui-recovery',{create:true});const file=await directory.getFileHandle(id+'.json',{create:true}),stream=await file.createWritable();await stream.write(JSON.stringify({schemaVersion:1,id,copies}));await stream.close();},{id,copies});await page.getByRole('button',{name:'Elegir carpeta del proyecto'}).click();await expect(page.getByText('Hay un guardado pendiente de comprobar.')).toBeVisible();await page.getByRole('button',{name:'Activar Editor'}).click();await page.getByRole('button',{name:'Revisar recuperación'}).click();const review=page.getByRole('dialog',{name:'Revisar guardado interrumpido'});await expect(review.getByText('Contenido previsto guardado',{exact:true})).toBeVisible();await expect(review.getByText('Contenido original conservado',{exact:true})).toBeVisible();await expect(review.getByRole('button',{name:'Exportar copias'})).toBeEnabled();const downloadPromise=page.waitForEvent('download');await review.getByRole('button',{name:'Exportar copias'}).click();const download=await downloadPromise;const exported=JSON.parse(await readFile((await download.path())!,'utf8'));expect(exported.copies).toEqual(copies);
 await review.getByRole('button',{name:'Restaurar originales'}).click();await page.getByRole('dialog',{name:'Restaurar originales'}).getByRole('button',{name:'Confirmar restauración'}).click();await expect(page.getByText('Estado de los archivos comprobado. Puedes continuar los cambios pendientes.')).toBeVisible();for(const copy of copies)expect(await readFile(join(project,copy.path),'utf8')).toBe(copy.before);await expect(page.getByText('Hay un guardado pendiente de comprobar.')).toHaveCount(0);await expect(readFile(join(project,'.bmad-project-ui/local/write-recovery.json'))).rejects.toHaveProperty('code','ENOENT');
});

test('shows the limits of hash-only recovery without claiming unavailable backups',async({page,project})=>{
 const path='docs/notas/reunion.md',before=await readFile(join(project,path),'utf8');await mkdir(join(project,'.bmad-project-ui/local'),{recursive:true});await writeFile(join(project,'.bmad-project-ui/local/write-recovery.json'),JSON.stringify({schemaVersion:1,id:randomUUID(),createdAt:new Date().toISOString(),entries:[{path,before:hash(before),after:hash(before+'\nPlanned.')}]}));await page.goto('/');await page.getByRole('button',{name:'Elegir carpeta del proyecto'}).click();await page.getByRole('button',{name:'Revisar recuperación'}).click();const review=page.getByRole('dialog',{name:'Revisar guardado interrumpido'});await expect(review.getByText(/Este navegador no dispone de copias verificables/)).toBeVisible();await expect(review.getByRole('button',{name:'Restaurar originales'})).toHaveCount(0);await expect(review.getByRole('button',{name:'Aceptar el estado comprobado'})).toBeDisabled();expect(await readFile(join(project,path),'utf8')).toBe(before);
});

test('preserves an external recovery version and requires exporting copies before clearing the journal',async({page,project})=>{
 const path='docs/notas/reunion.md',before=await readFile(join(project,path),'utf8'),after=before+'\nGuardado interrumpido.\n',external=before+'\nCambio externo que debe conservarse.\n',id=randomUUID(),copies=[{path,before,after}];await writeFile(join(project,path),external);await mkdir(join(project,'.bmad-project-ui/local'),{recursive:true});await writeFile(join(project,'.bmad-project-ui/local/write-recovery.json'),JSON.stringify({schemaVersion:1,id,createdAt:new Date().toISOString(),entries:[{path,before:hash(before),after:hash(after)}]}));
 await page.goto('/');await page.evaluate(async({id,copies})=>{const directory=await(await navigator.storage.getDirectory()).getDirectoryHandle('bmad-project-ui-recovery',{create:true}),file=await directory.getFileHandle(id+'.json',{create:true}),stream=await file.createWritable();await stream.write(JSON.stringify({schemaVersion:1,id,copies}));await stream.close();},{id,copies});await page.getByRole('button',{name:'Elegir carpeta del proyecto'}).click();await page.getByRole('button',{name:'Activar Editor'}).click();await page.getByRole('button',{name:'Revisar recuperación'}).click();const review=page.getByRole('dialog',{name:'Revisar guardado interrumpido'});await expect(review.getByText(/La restauración está bloqueada para conservarla/)).toBeVisible();await expect(review.getByRole('button',{name:'Restaurar originales'})).toBeDisabled();await expect(review.getByRole('button',{name:'Completar guardado previsto'})).toBeDisabled();await expect(review.getByRole('button',{name:'Conservar archivos actuales'})).toBeDisabled();
 const downloadPromise=page.waitForEvent('download');await review.getByRole('button',{name:'Exportar copias'}).click();const download=await downloadPromise,exported=JSON.parse(await readFile((await download.path())!,'utf8'));expect(exported.copies).toEqual(copies);expect(exported.current[path]).toBe(external);expect(await readFile(join(project,path),'utf8')).toBe(external);await review.getByRole('button',{name:'Conservar archivos actuales'}).click();const confirmation=page.getByRole('dialog',{name:'Conservar los archivos actuales'});await expect(confirmation.getByText(/Se conservará la versión externa actual sin sobrescribirla/)).toBeVisible();await confirmation.getByRole('button',{name:'Confirmar y conservar estado actual'}).click();await expect(page.getByText('Hay un guardado pendiente de comprobar.')).toHaveCount(0);expect(await readFile(join(project,path),'utf8')).toBe(external);await expect(readFile(join(project,'.bmad-project-ui/local/write-recovery.json'))).rejects.toHaveProperty('code','ENOENT');
});
