import {test,expect} from './filesystem';
import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import type {Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

async function open(page:Page,file='reunion.md') {await page.goto('/');await page.getByRole('button',{name:'Elegir carpeta del proyecto'}).click();await page.getByRole('button',{name:file,exact:true}).click();}
async function source(page:Page) {await page.getByRole('button',{name:'Markdown',exact:true}).click();return page.getByLabel('Fuente Markdown');}

test('preserves BOM and CRLF through a browser edit, then honors an external LF reload',async({page,project})=>{
 const path=join(project,'docs/notas/reunion.md');const initial='\uFEFF# Documento con CRLF\r\n\r\nTexto original.\r\n';await writeFile(path,initial);
 await open(page);await page.getByRole('button',{name:'Activar Editor'}).click();const editor=await source(page);await editor.click();await editor.press('ControlOrMeta+End');await page.keyboard.insertText('Añadido.');await page.getByRole('button',{name:'Guardar',exact:true}).click();await expect(page.getByText('Guardado localmente y verificado.')).toBeVisible();expect(await readFile(path,'utf8')).toBe(initial+'Añadido.');
 const external='# Documento LF\n\nTexto desde otro editor.\n';await writeFile(path,external);await page.getByRole('button',{name:'Releer archivos'}).click();await expect(editor).toContainText('Texto desde otro editor.');await editor.click();await editor.press('ControlOrMeta+End');await page.keyboard.insertText('Segunda edición.');await page.getByRole('button',{name:'Guardar',exact:true}).click();await expect.poll(()=>readFile(path,'utf8')).toBe(external+'Segunda edición.');
});

test('guards drafts on file, mode and view changes with an explicit discard choice',async({page,project})=>{
 const path=join(project,'docs/notas/reunion.md'),before=await readFile(path,'utf8');await open(page);await page.getByRole('button',{name:'Activar Editor'}).click();const editor=await source(page);await editor.click();await editor.press('ControlOrMeta+End');await editor.press('Enter');await page.keyboard.insertText('Borrador protegido.');
 const exported=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar borrador'}).click();const download=await exported;expect(await readFile((await download.path())!,'utf8')).toBe(before+'\nBorrador protegido.');
 for(const label of ['riego.md','Volver a lectura','Historias']){await page.getByRole('button',{name:label,exact:true}).click();const guard=page.getByRole('dialog',{name:'Hay cambios sin guardar'});await expect(guard).toBeVisible();await guard.getByRole('button',{name:'Seguir aquí'}).click();await expect(editor).toContainText('Borrador protegido.');}
 await page.getByRole('button',{name:'riego.md',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Descartar borradores y continuar'}).click();await expect(page.getByRole('heading',{name:'Riego',exact:true})).toBeVisible();expect(await readFile(path,'utf8')).toBe(before);
});

test('follows relative document links and headings and reports a broken target',async({page,project})=>{
 await writeFile(join(project,'docs/manual/index.md'),'# Manual\n\n[Riego con sección](riego.md#turnos)\n\n[Ausente](no-existe.md)\n\n[Sección ausente](#no-existe)\n');await open(page,'index.md');await page.getByRole('link',{name:'Riego con sección'}).click();await expect(page.getByRole('heading',{name:'Turnos',exact:true})).toBeVisible();await page.getByRole('button',{name:'index.md',exact:true}).click();await page.getByRole('link',{name:'Sección ausente'}).click();await expect(page.getByText('No se encuentra la sección «no-existe» en este documento.')).toBeVisible();await page.getByRole('link',{name:'Ausente',exact:true}).click();await expect(page.getByRole('heading',{name:'No se encuentra el archivo'})).toBeVisible();await page.getByRole('button',{name:'reunion.md',exact:true}).click();await expect(page.getByRole('heading',{name:'Reunión de prueba'})).toBeVisible();
});

test('reviews a story state and checklist change against their actual source files',async({page,project})=>{
 await open(page);await page.getByRole('button',{name:'Activar Editor'}).click();await page.getByRole('button',{name:'Historias',exact:true}).click();await page.getByLabel('Buscar historia').fill('Reservar turno');await page.getByRole('button',{name:/Reservar turno/}).click();let dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Editar campos'}).click();await dialog.getByRole('combobox',{name:'Campo',exact:true}).selectOption('status');await dialog.getByRole('combobox',{name:'Nuevo valor',exact:true}).selectOption('in-progress');await dialog.getByRole('button',{name:'Revisar cambios',exact:true}).click();await expect(dialog).toContainText('sprint-status.yaml');await dialog.getByRole('button',{name:'Confirmar y guardar'}).click();await expect(page.getByRole('region',{name:'En progreso',exact:true}).getByRole('button',{name:/Reservar turno/})).toBeVisible();const sprint=await readFile(join(project,'_bmad-output/implementation-artifacts/sprint-status.yaml'),'utf8');expect(sprint).toContain('1-2-reservar-turno: in-progress');expect(sprint).toContain('custom_fixture_field: preserve-me');
 await page.getByLabel('Buscar historia').fill('Consultar parcelas');await page.getByRole('button',{name:/Consultar parcelas/}).click();dialog=page.getByRole('dialog');await dialog.getByRole('checkbox',{name:'Validar navegación por teclado'}).click();await expect(dialog).toContainText('1-1-consultar-parcelas.md');await dialog.getByRole('button',{name:'Confirmar y guardar'}).click();await expect.poll(()=>readFile(join(project,'_bmad-output/implementation-artifacts/1-1-consultar-parcelas.md'),'utf8')).toContain('- [x] Validar navegación por teclado');
});

test('isolates malformed comments and integration sidecars without crashing the reader',async({page,project})=>{
 await mkdir(join(project,'.bmad-project-ui/comments/threads'),{recursive:true});await mkdir(join(project,'.bmad-project-ui/integrations'),{recursive:true});const damaged='{"schemaVersion":1,"id":"broken","messages":[null]}';await writeFile(join(project,'.bmad-project-ui/comments/threads/broken.json'),damaged);await writeFile(join(project,'.bmad-project-ui/integrations/jira.json'),JSON.stringify({schemaVersion:1,projectId:'test',bases:{},bindings:[{schemaVersion:1,normalizerVersion:1,id:'binding',projectId:'test',provider:'jira',deployment:'cloud',instance:'https://tenant.example.test',resourceId:'1',resourceUrl:'https://tenant.example.test/browse/TEST-1',scopeId:'1',local:{path:'docs/notas/reunion.md'},fields:null,policy:'review-both-directions'}]}));const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await open(page);await page.getByRole('button',{name:'Comentarios',exact:true}).click();await expect(page.getByText('Hay 1 archivos de comentarios que no se pudieron leer. Se conservan sin cambios.')).toBeVisible();await page.getByRole('button',{name:/Conexión con Jira/}).click();await expect(page.getByText(/No se puede interpretar la configuración/)).toBeVisible();await page.getByRole('button',{name:'Documentos',exact:true}).click();await expect(page.getByRole('heading',{name:'Reunión de prueba'})).toBeVisible();expect(errors).toEqual([]);expect(await readFile(join(project,'.bmad-project-ui/comments/threads/broken.json'),'utf8')).toBe(damaged);
});

test('renders the selected C1 desktop layout, centered T2, and a usable narrow board',async({page,project},info)=>{
 void project;await page.setViewportSize({width:1440,height:1000});await open(page);await page.getByRole('button',{name:'Comentarios',exact:true}).click();await page.screenshot({path:info.outputPath('c1-reader-comments.png'),fullPage:true});await page.getByRole('button',{name:'Historias',exact:true}).click();await page.screenshot({path:info.outputPath('c1-board.png'),fullPage:true});await page.getByLabel('Buscar historia').fill('Reservar turno');await page.getByRole('button',{name:/Reservar turno/}).click();const dialog=page.getByRole('dialog');const box=await dialog.boundingBox();expect(box?.width).toBeLessThanOrEqual(640);expect(Math.abs((box!.x+box!.width/2)-720)).toBeLessThan(2);expect(Math.abs((box!.y+box!.height/2)-500)).toBeLessThan(2);await page.screenshot({path:info.outputPath('t2-story-modal.png'),fullPage:true});await page.keyboard.press('Escape');await page.getByLabel('Buscar historia').fill('');await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath('c1-board-narrow.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const results=await new AxeBuilder({page}).analyze();expect(results.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);
});

test('maps a rendered Unicode selection to exact source, then explicitly reanchors moved content',async({page,project})=>{
 await open(page);await page.getByRole('button',{name:'Activar Editor'}).click();const quote='Lucía recibe agua 💧';await page.locator('article [data-source-start]').filter({hasText:'La parcela de Lucía'}).evaluate((element,selected)=>{const text=element.firstChild!;const from=text.textContent!.indexOf(selected);const range=document.createRange();range.setStart(text,from);range.setEnd(text,from+selected.length);const selection=window.getSelection()!;selection.removeAllRanges();selection.addRange(range);element.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));},quote);
 await page.getByRole('button',{name:'Comentar fragmento',exact:true}).click();await page.getByLabel('Tu nombre',{exact:true}).fill('Revisora Unicode');await page.getByRole('button',{name:'Usar este nombre'}).click();await page.getByLabel('Nuevo comentario',{exact:true}).fill('Selección exacta con acento y emoji.');await page.getByRole('button',{name:'Guardar comentario',exact:true}).click();await expect(page.getByRole('region',{name:'Mensaje de Revisora Unicode'}).getByText('Selección exacta con acento y emoji.',{exact:true})).toBeVisible();const folder=join(project,'.bmad-project-ui/comments/threads');const [filename]=await readdir(folder);const first=JSON.parse(await readFile(join(folder,filename),'utf8'));expect(first.anchor.quote).toBe(quote);const file=join(project,'docs/notas/reunion.md'),before=await readFile(file,'utf8');expect(before.slice(first.anchor.startOffset,first.anchor.endOffset)).toBe(quote);
 await writeFile(file,'Una nota añadida antes.\n\n'+before);await page.getByRole('button',{name:'Releer archivos'}).click();await expect(page.getByText(/Fragmento reubicado en esta vista/)).toBeVisible();expect(JSON.parse(await readFile(join(folder,filename),'utf8')).anchor).toEqual(first.anchor);
 await page.getByRole('button',{name:'Reanclar',exact:true}).click();await page.getByLabel('Línea inicial').fill('5');await page.getByLabel('Línea final').fill('5');await page.getByRole('button',{name:'Seleccionar',exact:true}).click();await page.getByRole('button',{name:'Confirmar nuevo fragmento'}).click();await expect(page.getByText(/Fragmento localizado/)).toBeVisible();const moved=JSON.parse(await readFile(join(folder,filename),'utf8'));expect(moved.anchor.quote).toBe('Nota original para editar y comentar desde el navegador.');expect(moved.events.at(-1).previousAnchor).toEqual(first.anchor);
});

test('keeps local files intact when write permission is denied',async({page,project})=>{
 await open(page);const before=await readFile(join(project,'docs/notas/reunion.md'),'utf8');await page.evaluate(()=>{(window as unknown as {__testPermission:string}).__testPermission='denied';});await page.getByRole('button',{name:'Activar Editor'}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('button',{name:'Activar Editor'})).toBeVisible();expect(await readFile(join(project,'docs/notas/reunion.md'),'utf8')).toBe(before);await expect(page.getByRole('button',{name:'Guardar',exact:true})).toHaveCount(0);
});

test('keeps layouts within the viewport at documented breakpoints and traps modal keyboard focus',async({page,project},info)=>{
 void project;await open(page);await page.getByRole('button',{name:'Comentarios',exact:true}).click();for(const width of [1440,1061,1060,1059,1024,851,850,849,681,680,679,651,650,649,580,401,400,399,390,320]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`reader at ${width}px`).toBe(true);if([1024,650,320].includes(width))await page.screenshot({path:info.outputPath(`reader-${width}.png`),fullPage:false});}
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Historias',exact:true}).click();const card=page.getByRole('button',{name:/Reservar turno/});await card.click();const dialog=page.getByRole('dialog');for(let i=0;i<12;i++){await page.keyboard.press('Tab');expect(await dialog.evaluate(element=>element.contains(document.activeElement))).toBe(true);}await page.keyboard.press('Escape');await expect(card).toBeFocused();
 await page.evaluate(()=>{document.body.style.zoom='200%';});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('board-css-zoom-200.png'),fullPage:false});
});

test('edits a visual text leaf while preserving Markdown structure and metadata',async({page,project})=>{
 const path=join(project,'docs/notas/reunion.md');const before='---\ntitle: Nota original\nstatus: draft\n---\n# Nota original\n\nTexto **importante** y final.\n';await writeFile(path,before);await open(page);await page.getByRole('button',{name:'Activar Editor'}).click();const leaf=page.getByRole('textbox',{name:'Editar texto de la línea 7'}).filter({hasText:'importante'});await leaf.fill('clave');await page.getByRole('button',{name:'Guardar',exact:true}).click();await expect(page.getByText('Guardado localmente y verificado.')).toBeVisible();expect(await readFile(path,'utf8')).toBe(before.replace('**importante**','**clave**'));await page.getByRole('button',{name:'Markdown',exact:true}).click();await expect(page.getByLabel('Fuente Markdown')).toContainText('Texto **clave** y final.');
});

test('loads authorized local raster images and blocks remote, active and escaping references',async({page,project})=>{
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jK+0AAAAASUVORK5CYII=','base64');await mkdir(join(project,'docs/assets'),{recursive:true});await writeFile(join(project,'docs/assets/pixel.png'),png);await writeFile(join(project,'docs/assets/active.svg'),'<svg xmlns="http://www.w3.org/2000/svg" onload="window.__unsafeImage=true"><image href="https://example.com/tracker"/></svg>');const markdown='# Imágenes\n\n![Pixel local](../assets/pixel.png)\n\n![Remota](https://example.com/tracker.png)\n\n![SVG activo](../assets/active.svg)\n\n![Fuera](../../../../private.png)\n';await writeFile(join(project,'docs/notas/reunion.md'),markdown);const remote:string[]=[];page.on('request',request=>{if(request.url().startsWith('https://example.com'))remote.push(request.url());});await open(page);const image=page.getByRole('img',{name:'Pixel local'});await expect(image).toBeVisible();await expect.poll(()=>image.evaluate((element:HTMLImageElement)=>element.complete&&element.naturalWidth===1)).toBe(true);await expect(image).toHaveAttribute('src',/^blob:/);await expect(page.getByText('Imagen remota bloqueada; no se carga al abrir el documento.')).toBeVisible();await expect(page.getByText(/Vista previa disponible para PNG, JPEG, GIF y WebP/)).toBeVisible();await expect(page.getByText('Ruta de imagen no compatible o fuera del proyecto.')).toBeVisible();expect(remote).toEqual([]);expect(await page.evaluate(()=>('__unsafeImage' in window))).toBe(false);const originalUrl=(await image.getAttribute('src'))!;await writeFile(join(project,'docs/assets/pixel.png'),Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7','base64'));await page.getByRole('button',{name:'Releer archivos',exact:true}).click();await expect(image).not.toHaveAttribute('src',originalUrl);await expect.poll(()=>image.evaluate((element:HTMLImageElement)=>element.complete&&element.naturalWidth===1)).toBe(true);expect(await page.evaluate(async url=>{try{await fetch(url);return true;}catch{return false;}},originalUrl)).toBe(false);expect(await readFile(join(project,'docs/notas/reunion.md'),'utf8')).toBe(markdown);
});
