import { useEffect, useMemo, useRef, useState } from 'react';
import { Link2, Plug, Search, RefreshCw, ArrowLeftRight, Download, Unplug } from 'lucide-react';
import {captureBase,fieldEqual,localFields} from '../../../../packages/integrations/src/index';
import { visibleWorkItems, type FileChange } from '../../../../packages/domain/src/index';
import { AtlassianClient, type Provider, type IntegrationPlan, type IntegrationBinding, type RemoteResource, type ResourceSummary, type Scope, type AdapterCapabilities, type ManagedField, type Direction, type IntegrationOperation, type LocalResource, type HistoryEntry } from '../services/atlassian-client';
import { loadIntegrationState, saveIntegrationBinding, unlinkIntegrationBinding, importIntegrationPlan, exportIntegrationPlan, saveIntegrationConnection, previewIntegrationImport, getComparisonBase, saveComparisonBase, comparisonBasePersistence } from '../services/integration-state';
import type { ProjectStore, ProjectSnapshot } from '../services/project-store';
import { Dialog } from './Dialog';
import styles from '../App.module.css';

const providerName={jira:'Jira',confluence:'Confluence'};
const fieldName:Record<ManagedField,string>={title:'Título',description:'Descripción',body:'Documento',status:'Estado'};
const comparisonName:Record<string,string>={equal:'Coinciden', 'no-base':'Sin base común','local-changes':'Cambios locales','remote-changes':'Cambios remotos','both-changed':'Cambios en ambos',convergent:'Cambios convergentes',partial:'Comparación parcial'};
const explain=(error:unknown)=>error instanceof Error?error.message:String(error);
export function indeterminateAtlassianApply(error:unknown){const code=(error as {code?:string})?.code;return !['plan_expired','plan_not_found','blocked_plan','remote_stale','scope_mismatch','session_expired','resource_busy','invalid_operation','invalid_content_type','invalid_plan','journal_locked','reconciliation_required'].includes(code??'');}
export function AtlassianPanel({provider,store,snapshot,activePath,hidden,dirty,saving,onStatus,onBusy,onRefresh}:{provider:Provider;store:ProjectStore;snapshot:ProjectSnapshot;activePath:string;hidden:boolean;dirty:boolean;saving:boolean;onStatus:(value:string)=>void;onBusy:(busy:boolean)=>void;onRefresh:()=>Promise<void>}) {
  const name=providerName[provider],defaultEndpoint=provider==='jira'?'http://127.0.0.1:43121':'http://127.0.0.1:43122';
  const saved=useMemo(()=>{try{return {...loadIntegrationState(snapshot,provider),corrupt:''};}catch(error){return {path:`.bmad-project-ui/integrations/${provider}.json`,revision:null,state:{schemaVersion:1 as const,projectId:'unavailable',bindings:[] as IntegrationBinding[],bases:{}},corrupt:explain(error)};}},[snapshot,provider]);
  const [client,setClient]=useState<AtlassianClient|null>(null),[draftClient,setDraftClient]=useState<AtlassianClient|null>(null),[endpoint,setEndpoint]=useState(defaultEndpoint),[token,setToken]=useState(''),[wizard,setWizard]=useState<number|null>(null),[scopes,setScopes]=useState<Scope[]>([]),[scopeId,setScopeId]=useState(''),[localRoot,setLocalRoot]=useState(''),[capabilities,setCapabilities]=useState<AdapterCapabilities|null>(null),[checked,setChecked]=useState(false),[checkRows,setCheckRows]=useState<{label:string;value:string}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[results,setResults]=useState<ResourceSummary[]>([]),[complete,setComplete]=useState(true),[candidate,setCandidate]=useState<RemoteResource|null>(null),[bindingId,setBindingId]=useState(''),[resource,setResource]=useState<RemoteResource|null>(null),[history,setHistory]=useState<HistoryEntry[]>([]),[localChoice,setLocalChoice]=useState(''),[fields,setFields]=useState<ManagedField[]>(provider==='jira'?['title','description']:['title','body']),[direction,setDirection]=useState<Direction>('publish'),[plan,setPlan]=useState<IntegrationPlan|null>(null),[reviewOpen,setReviewOpen]=useState(false),[operation,setOperation]=useState<IntegrationOperation|null>(null),[lostPlan,setLostPlan]=useState(''),[unlinking,setUnlinking]=useState(false),[transitionId,setTransitionId]=useState(''),[featureId,setFeatureId]=useState(''),[importChanges,setImportChanges]=useState<FileChange[]|null>(null),[importError,setImportError]=useState('');
  const [pendingOperations,setPendingOperations]=useState<IntegrationOperation[]>([]),[pendingWarning,setPendingWarning]=useState('');
  const generation=useRef(0);
  const reviewedMapping=useRef<{revision:string|null;bindingId:string;binding:string;connection:string}|null>(null);
  const priorWizard=useRef({scopeId:'',localRoot:'',capabilities:null as AdapterCapabilities|null,scopes:[] as Scope[],endpoint:defaultEndpoint});
  const currentBinding=saved.state.bindings.find(binding=>binding.id===bindingId)??saved.state.bindings[0];
  const projected=visibleWorkItems(snapshot.index);
  const localOptions=provider==='jira'?projected.filter(item=>item.kind==='story'||item.kind==='epic'||item.kind==='action').map(item=>({id:item.id,path:item.documentPath??item.source.path,title:`${item.nativeId??item.id} · ${item.title}`,item})):snapshot.index.documents.filter(doc=>/\.md$/i.test(doc.path)).map(doc=>({id:doc.path,path:doc.path,title:doc.path,item:undefined}));
  const roots=['',...new Set(snapshot.index.roots.filter(root=>root.exists).map(root=>root.path)),...new Set(snapshot.index.documents.map(doc=>doc.path.split('/').slice(0,-1).join('/')).filter(Boolean))].filter((path,index,list)=>list.indexOf(path)===index);
  const eligible=localOptions.filter(option=>!localRoot||option.path===localRoot||option.path.startsWith(localRoot+'/'));
  const option=eligible.find(option=>option.id===localChoice)??eligible.find(option=>option.path===activePath)??eligible[0];
  const jiraBindings=useMemo(()=>{try{return provider==='confluence'?loadIntegrationState(snapshot,'jira').state.bindings:[];}catch{return [];}},[snapshot,provider]);
  const recovery=pendingOperations.length>0||!!pendingWarning||!!lostPlan||operation?.status==='uncertain'||operation?.status==='running'||operation?.status==='partial'||operation?.status==='prepared';
  const canConfigure=store.mode==='edit'&&!dirty&&!saving&&!busy&&!store.recoveryPending&&!saved.corrupt;const canWrite=canConfigure&&!recovery;
  useEffect(()=>{onStatus(client?.connected?'Conectado':'No conectado');},[client,onStatus]);
  useEffect(()=>{generation.current++;setClient(null);setDraftClient(null);setWizard(null);setToken('');setChecked(false);setPlan(null);setResource(null);setCandidate(null);setOperation(null);setPendingOperations([]);setPendingWarning('');setLostPlan('');setBindingId('');},[store]);
  useEffect(()=>{if(hidden&&wizard!==null)void cancelWizard();},[hidden]);
  useEffect(()=>{if(plan&&snapshot.revisions[plan.local.path]!==plan.local.revision){setPlan(null);setReviewOpen(false);setImportChanges(null);setNotice('El archivo local ha cambiado. Compara de nuevo antes de aplicar.');}},[snapshot]);
  useEffect(()=>{if(resource&&(!currentBinding||resource.id!==currentBinding.resourceId||resource.instance!==currentBinding.instance)){setResource(null);setPlan(null);setHistory([]);setReviewOpen(false);}},[currentBinding?.id]);
  useEffect(()=>{if(plan&&reviewedMapping.current&&(saved.revision!==reviewedMapping.current.revision||JSON.stringify(currentBinding)!==reviewedMapping.current.binding||JSON.stringify('connection' in saved.state?saved.state.connection:null)!==reviewedMapping.current.connection)){setPlan(null);setReviewOpen(false);setImportChanges(null);setNotice('La asociación o su ámbito han cambiado. Compara de nuevo antes de aplicar.');}},[plan,saved.revision,currentBinding]);
  async function run(action:()=>Promise<void>,mutation=false){setBusy(true);setError('');setNotice('');if(mutation)onBusy(true);try{await action();}catch(error){const code=(error as {code?:string})?.code;if(code==='session_expired'||code==='provider_auth_expired'){void client?.disconnect().catch(()=>undefined);setClient(null);setPlan(null);setResource(null);setReviewOpen(false);}setError(explain(error));}finally{setBusy(false);if(mutation)onBusy(false);}}
  function invalidate(){setPlan(null);setReviewOpen(false);setCandidate(null);setResource(null);setHistory([]);setChecked(false);}
  function startWizard(){priorWizard.current={scopeId,localRoot,capabilities,scopes,endpoint};const connection=('connection' in saved.state?saved.state.connection:undefined) as {scopeId?:string;localRoot?:string}|undefined;if(!client&&connection){setScopeId(connection.scopeId??'');setLocalRoot(connection.localRoot==='.'?'':connection.localRoot??'');}setWizard(0);setDraftClient(null);setChecked(false);setCheckRows([]);setToken('');setError('');setScopes([]);generation.current++;}
  async function cancelWizard(){generation.current++;const temporary=draftClient;setDraftClient(null);setWizard(null);setChecked(false);setToken('');setError('');setScopeId(priorWizard.current.scopeId);setLocalRoot(priorWizard.current.localRoot);setCapabilities(priorWizard.current.capabilities);setScopes(priorWizard.current.scopes);setEndpoint(priorWizard.current.endpoint);if(temporary&&temporary!==client)await temporary.disconnect().catch(()=>undefined);}
  async function authorize(){await run(async()=>{const version=++generation.current;const active=new AtlassianClient(provider,endpoint);await active.health();const authorized=await active.authorize(token);if(version!==generation.current){await active.disconnect();return;}const page=await active.scopes();if(version!==generation.current){await active.disconnect();return;}setDraftClient(active);setCapabilities(authorized.capabilities);setScopes(page.items);setComplete(page.complete);setScopeId(page.items.some(scope=>scope.id===scopeId)?scopeId:page.items[0]?.id??'');setToken('');setWizard(3);});}
  async function check(){if(!draftClient||!scopeId)return;await run(async()=>{const version=++generation.current;setChecked(false);setCheckRows([{label:'Identidad y servicio',value:'Comprobando…'},{label:'Ámbito y permisos',value:'Pendiente'},{label:'Lectura de un recurso',value:'Pendiente'},{label:'Cobertura del listado',value:'Pendiente'}]);const caps=await draftClient.capabilities(),page=await draftClient.search(scopeId,'');if(version!==generation.current)return;setCapabilities(caps);setComplete(page.complete);if(!caps.read)throw new Error('La cuenta está reconocida, pero no dispone de lectura en este servicio.');if(!page.complete)throw new Error('El listado no está completo. No se puede confirmar la cobertura del ámbito.');if(!page.items.length)throw new Error('No hay un recurso accesible para comprobar este ámbito. Revisa el destino.');const observed=await draftClient.resource(page.items[0].id);if(version!==generation.current)return;if(observed.scopeId!==scopeId)throw new Error('El recurso comprobado no pertenece al ámbito elegido.');setCheckRows([{label:'Identidad y servicio',value:`${draftClient.identity?.displayName??'Identidad no disponible'} · ${name} · ${draftClient.instance}`},{label:'Ámbito y permisos',value:`Lectura permitida · ${scopes.find(scope=>scope.id===scopeId)?.name??scopeId}`},{label:'Lectura de un recurso',value:`${observed.key??observed.id} · ${observed.title}`},{label:'Cobertura del listado',value:'Completa para el ámbito consultado'}]);setChecked(true);});}
  async function discoverPending(active:AtlassianClient){const page=await active.pendingOperations();const pending=page.items.filter(item=>['prepared','running','uncertain','partial'].includes(item.status));setPendingOperations(pending);setPendingWarning(page.complete?page.warnings.join(' '):'El historial de operaciones está incompleto. Consulta el registro del conector antes de volver a aplicar cambios. '+page.warnings.join(' '));if(pending.length)setOperation(current=>pending.find(item=>item.id===current?.id)??pending[0]);}
  async function saveConnection(){if(!draftClient||!capabilities||!checked)return;await run(async()=>{if(recovery&&operation&&draftClient.instance!==operation.instance)throw new Error('Hay una operación pendiente en otra instancia. Vuelve a conectar esa instancia para comprobarla.');await discoverPending(draftClient);await saveIntegrationConnection(store,snapshot,provider,{instance:draftClient.instance,deployment:capabilities.deployment,scopeId,scopeName:scopes.find(scope=>scope.id===scopeId)?.name??scopeId,localRoot:localRoot||'.',checkedAt:new Date().toISOString()});setClient(draftClient);setDraftClient(null);setWizard(null);invalidate();setChecked(true);await onRefresh();setNotice(`Conexión con ${name} guardada. El siguiente paso es vincular un recurso existente.`);},true);}
  async function search(){if(!client)return;await run(async()=>{setCandidate(null);const page=await client.search(scopeId,query);setResults(page.items);setComplete(page.complete);if(page.warnings.length)setNotice(page.warnings.join(' '));});}
  async function inspect(id:string){if(!client)return;await run(async()=>{const item=await client.resource(id);if(item.instance!==client.instance||item.scopeId!==scopeId)throw new Error('El candidato no pertenece a la instancia y ámbito autorizados.');setCandidate(item);});}
  async function link(){if(!candidate||!option||!capabilities)return;await run(async()=>{if(saved.state.bindings.some(binding=>binding.instance===candidate.instance&&binding.resourceId===candidate.id&&(binding.local.path!==option.path||binding.local.entityId!==option.item?.id)))throw new Error('Este recurso remoto ya está vinculado a otro elemento local. Revisa ese vínculo antes de continuar.');const feature=jiraBindings.find(binding=>binding.id===featureId);const binding:IntegrationBinding={schemaVersion:1,id:crypto.randomUUID(),projectId:saved.state.projectId,provider,deployment:capabilities.deployment,instance:candidate.instance,resourceId:candidate.id,resourceKey:candidate.key,resourceUrl:candidate.url,scopeId:candidate.scopeId,local:{path:option.path,entityId:option.item?.id,kind:option.item?.kind??'document'},fields,policy:'review-both-directions',normalizerVersion:1,...(feature?{feature:{instance:feature.instance,issueId:feature.resourceId,key:feature.resourceKey}}:{})};await saveIntegrationBinding(store,snapshot,binding);setBindingId(binding.id);setResource(candidate);setCandidate(null);setPlan(null);await onRefresh();setNotice('Vínculo guardado. No se ha publicado ni importado contenido.');},true);}
  async function openBinding(binding:IntegrationBinding){if(!client)return;setBindingId(binding.id);setPlan(null);setImportChanges(null);setResource(null);setCandidate(null);setFields(binding.fields);setTransitionId('');await run(async()=>{const remote=await client.resource(binding.resourceId);if(remote.instance!==binding.instance)throw new Error('La instancia conectada no coincide con la identidad guardada en el vínculo.');setResource(remote);setHistory((await client.history(binding.resourceId)).items);});}
  function localForBinding(binding:IntegrationBinding,context=snapshot):LocalResource {const item=binding.local.entityId?context.index.workItems.find(item=>item.id===binding.local.entityId):undefined;const source=context.files[binding.local.path];if(source===undefined)throw new Error('El archivo vinculado no está disponible en esta rama.');if(binding.local.entityId&&!item)throw new Error('No se encuentra el elemento local vinculado. Revisa su identidad antes de continuar.');return {path:binding.local.path,revision:context.revisions[binding.local.path],text:provider==='jira'?item?.description??'':source,title:item?.title??context.index.documents.find(doc=>doc.path===binding.local.path)?.title,status:item?.status?.raw,entityId:item?.id};}
  async function advanceBase(reviewed:IntegrationPlan,remote:RemoteResource,context:ProjectSnapshot){if(!currentBinding||currentBinding.resourceId!==remote.id||currentBinding.instance!==remote.instance)return;const local=localForBinding(currentBinding,context),captured=captureBase(local,remote),previous=await getComparisonBase(store,context,provider,currentBinding.id);const next={...captured,local:{...previous?.local},remote:{...previous?.remote}};for(const field of reviewed.fields){next.local[field]=captured.local[field];next.remote[field]=captured.remote[field];}await saveComparisonBase(store,context,provider,currentBinding.id,next);}
  async function compare(){if(!client||!currentBinding)return;await run(async()=>{reviewedMapping.current={revision:saved.revision,bindingId:currentBinding.id,binding:JSON.stringify(currentBinding),connection:JSON.stringify('connection' in saved.state?saved.state.connection:null)};const prepared=await client.plan({resourceId:currentBinding.resourceId,scopeId:currentBinding.scopeId,local:localForBinding(currentBinding),base:await getComparisonBase(store,snapshot,provider,currentBinding.id),direction,fields,transitionId:transitionId||undefined});if(prepared.resource.instance!==currentBinding.instance)throw new Error('La instancia del plan no coincide con la asociación revisada.');setPlan(prepared);});}
  async function review(){if(!plan)return;setImportChanges(null);setImportError('');setReviewOpen(true);if(plan.direction==='import'&&!plan.blockedReasons.length){try{setImportChanges(await previewIntegrationImport(snapshot,plan));}catch(error){setImportError(explain(error));}}}
  async function apply(){if(!plan||!client||!canWrite)return;const reviewed=plan;setReviewOpen(false);await run(async()=>{const fresh=await store.refresh(),mapping=loadIntegrationState(fresh,provider),context=reviewedMapping.current;if(!context||mapping.revision!==context.revision||JSON.stringify(mapping.state.bindings.find(binding=>binding.id===context.bindingId))!==context.binding||JSON.stringify(mapping.state.connection??null)!==context.connection){setPlan(null);await onRefresh();throw new Error('La asociación o su ámbito cambiaron después de revisar. Compara de nuevo antes de aplicar.');}if(fresh.revisions[reviewed.local.path]!==reviewed.local.revision){setPlan(null);await onRefresh();throw new Error('El archivo local cambió después de revisar. Compara de nuevo antes de aplicar.');}if(reviewed.direction==='import'){if(!importChanges)throw new Error('Revisa las diferencias exactas de los archivos antes de importar.');const latest=await client.resource(reviewed.resource.id);if(latest.instance!==reviewed.resource.instance||latest.scopeId!==reviewed.resource.scopeId||latest.version!==reviewed.resource.version||reviewed.fields.some(field=>latest.fields[field]!==reviewed.resource.fields[field]))throw new Error('El recurso remoto cambió después de revisar. Compara de nuevo antes de importar.');await importIntegrationPlan(store,reviewed,{confirmed:true,reviewedChanges:importChanges});await advanceBase(reviewed,latest,await store.refresh());setPlan(null);await onRefresh();setNotice('Importación guardada localmente y verificada. Git no se ha modificado.');}else{try{const result=await client.apply(reviewed.id);setOperation(result);setLostPlan('');if(result.status==='verified'){setPlan(null);setNotice('Campos remotos verificados.');try{const observed=await client.resource(reviewed.resource.id),values=localFields(reviewed.local);if(reviewed.fields.every(field=>fieldEqual(field,values[field]??'',observed.fields[field]??'')))await advanceBase(reviewed,observed,snapshot);}catch{setNotice('Los campos remotos se verificaron, pero no se pudo guardar una base nueva. Vuelve a comparar.');}}}catch(error){if(indeterminateAtlassianApply(error))setLostPlan(reviewed.id);else{setLostPlan('');setPlan(null);if((error as {code?:string}).code==='reconciliation_required')await discoverPending(client).catch(()=>undefined);}throw error;}}},true);}
  async function reconcile(){if(!client)return;await run(async()=>{const recorded=operation??(lostPlan?await client.operationByPlan(lostPlan):null);if(!recorded)throw new Error('No se dispone todavía de evidencia suficiente del resultado.');const result=await client.reconcile(recorded.id);setOperation(result);setPendingOperations(current=>current.map(item=>item.id===result.id?result:item).filter(item=>!['verified','rejected'].includes(item.status)));setLostPlan('');if(result.status==='verified'){setNotice('El resultado de la operación se ha verificado sin reenviarla.');if(plan&&plan.id===result.planId){try{const remote=await client.resource(plan.resource.id),values=localFields(plan.local);if(plan.fields.every(field=>fieldEqual(field,values[field]??'',remote.fields[field]??'')))await advanceBase(plan,remote,await store.refresh());}catch{/* Verification remains valid even when a later base cannot be captured. */}}}},true);}
  function exportCandidate(){if(!plan)return;const blob=new Blob([exportIntegrationPlan(plan)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`bmad-${provider}-plan-${plan.id}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const blocking=[...(plan?.blockedReasons??[]),...(importError?[importError]:[]),...(saved.corrupt?[saved.corrupt]:[]),...(store.recoveryPending?['Comprueba el guardado local pendiente antes de continuar.']:[]),...(dirty?['Guarda o descarta el borrador local antes de aplicar.']:[]),...(store.mode!=='edit'?['Activa Editor para aplicar cambios.']:[]),...(recovery?['Comprueba la operación pendiente antes de preparar otra.']:[])];
  return <main hidden={hidden} className={`${styles.content} ${styles.connectionPage}`}>
    <div className={styles.contentTitle}><div><h1>Conexión con {name}</h1><p className={styles.muted}>Vincula, compara y revisa los cambios de cada recurso.</p></div><span className={styles.badge} data-status={client?.connected?'done':'backlog'}>{client?.connected?'Conectado para consultar':'No conectado'}</span></div>
    {saved.corrupt&&<div role="alert" className={`${styles.banner} ${styles.bannerError}`}>No se puede interpretar la configuración de esta integración. {saved.corrupt} Los archivos originales se conservan.</div>}
    {error&&<div role="alert" className={`${styles.banner} ${styles.bannerError}`} style={{margin:'16px 0'}}>{error}</div>}{notice&&<p role="status" className={`${styles.banner} ${styles.bannerInfo}`} style={{margin:'16px 0'}}>{notice}</p>}
    {wizard===null?<>
      {!client?<><p>El conector de {name} es independiente de Git y de la otra integración. Tus documentos siguen disponibles sin conectar ninguna cuenta.</p><button className="primary" onClick={startWizard}><Plug size={16}/>Configurar conexión</button><details><summary>Preparar el conector local</summary><p>Configura la instancia y las credenciales del proveedor en el conector de tu equipo. La web solo utiliza su archivo de sesión local.</p><p>El paquete de conectores incluye el runtime. Consulta su guía de inicio y vuelve aquí cuando esté abierto.</p></details></>:<section className={styles.listItem}><h2>{client.instance}</h2><p className={styles.muted}>{capabilities?.deployment==='cloud'?'Cloud':'Data Center'} · {capabilities?.profile} · {scopes.find(scope=>scope.id===scopeId)?.name??scopeId}</p><p>Ámbito local: <code>{localRoot||'Raíz del proyecto'}</code></p><p className={styles.muted}>La conexión comprueba acceso; no significa que el contenido esté sincronizado.</p><div className={styles.actions}><button disabled={busy||recovery} onClick={startWizard}>Revisar configuración</button><button disabled={busy||recovery} onClick={()=>void run(async()=>{await client.disconnect();setClient(null);setPlan(null);setResource(null);setNotice('Conexión cerrada. Los vínculos y archivos se conservan.');})}><Unplug size={14}/>Desconectar</button></div></section>}
      {client&&<>
        <h2>Vínculos {name}</h2>{saved.state.bindings.length>0?<div className={styles.list}>{saved.state.bindings.map(binding=><button className={styles.listItem} style={{textAlign:'left',justifyContent:'space-between'}} key={binding.id} aria-pressed={binding.id===currentBinding?.id} disabled={busy||recovery} onClick={()=>void openBinding(binding)}><span>{binding.local.path}<br/><small>{binding.instance} · {binding.resourceKey??binding.resourceId}</small></span><ArrowLeftRight size={16}/></button>)}</div>:<p className={styles.muted}>Todavía no hay vínculos. Buscar un candidato no crea recursos remotos.</p>}
        <details className={styles.listItem} open={!saved.state.bindings.length} style={{marginTop:20}}><summary>Vincular {provider==='jira'?'una historia o épica':'un documento'} con un recurso existente</summary><div className={styles.form}><label>Elemento local<select value={option?.id??''} onChange={e=>{setLocalChoice(e.target.value);setCandidate(null);}} disabled={busy}><option value="" disabled>Selecciona un elemento</option>{eligible.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Buscar en {name}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={provider==='jira'?'Código o título de la incidencia':'Título de la página'} disabled={busy}/></label><div><button disabled={busy||!scopeId} onClick={()=>void search()}><Search size={15}/>Buscar candidatos</button></div></div>{!complete&&<div role="alert" className={styles.banner}>El listado está incompleto. No se interpreta la ausencia de un recurso como una eliminación.</div>}<div className={styles.list}>{results.map(item=><button key={item.id} onClick={()=>void inspect(item.id)} disabled={busy}>{item.key??item.id} · {item.title}</button>)}</div>
          {candidate&&<><div className={styles.diff}><section className={styles.listItem}><h3>Local</h3><strong>{option?.title}</strong><p className={styles.muted}>{option?.path}</p></section><section className={styles.listItem}><h3>{name}</h3><strong>{candidate.title}</strong><p className={styles.muted}>{candidate.instance} · ID {candidate.id} · {candidate.key} · ámbito {candidate.scopeId}</p></section></div>{provider==='confluence'&&<label>Relacionar con una feature de Jira (opcional)<select value={featureId} onChange={e=>setFeatureId(e.target.value)}><option value="">Sin relación adicional</option>{jiraBindings.map(binding=><option key={binding.id} value={binding.id}>{binding.resourceKey??binding.resourceId} · {binding.instance}</option>)}</select><p className={styles.muted}>La relación no copia el documento en Jira ni cambia el estado de la feature.</p></label>}<button className="primary" disabled={!canWrite||!option||!complete} onClick={()=>void link()}><Link2 size={15}/>Confirmar vínculo</button></>}
        </details>
        {resource&&currentBinding&&<section style={{marginTop:28}}><div className={styles.contentTitle}><div><h2>{resource.title}</h2><p className={styles.muted}>{resource.instance} · {resource.key??resource.id} · versión {resource.version}</p><p className={styles.muted}>{currentBinding.local.path}</p>{/^https:\/\//i.test(resource.url)&&<a href={resource.url} target="_blank" rel="noopener noreferrer">Abrir en {name}</a>}</div><button disabled={!canWrite} onClick={()=>setUnlinking(true)}>Quitar vínculo</button></div><div className={styles.actions}>{(capabilities?.fields??fields).map(field=><label className={styles.checkboxRow} key={field}><input type="checkbox" disabled={busy||recovery} checked={fields.includes(field)} onChange={event=>{setPlan(null);setFields(current=>event.target.checked?[...current,field]:current.filter(value=>value!==field));}}/>{fieldName[field]}</label>)}</div><div className={styles.form}><label>Dirección<select disabled={busy||recovery} value={direction} onChange={e=>{setPlan(null);setDirection(e.target.value as Direction);}}><option value="publish">Publicar local → {name}</option><option value="import">Traer {name} → local</option></select></label>{provider==='jira'&&fields.includes('status')&&<label>Transición explícita de Jira<select disabled={busy||recovery} value={transitionId} onChange={e=>{setTransitionId(e.target.value);setPlan(null);}}><option value="">Sin correspondencia confirmada</option>{resource.transitions?.map(transition=><option key={transition.id} value={transition.id}>{transition.name} → {transition.toStatusName} · ID {transition.id}{transition.requiredFields.length?` · requiere ${transition.requiredFields.join(', ')}`:''}</option>)}</select><small>Estado local: {snapshot.index.workItems.find(item=>item.id===currentBinding.local.entityId)?.status?.raw??'no declarado'}. El cambio solo se aplicará si el adaptador puede garantizarlo.</small></label>}<div><button disabled={busy||!fields.length||recovery} onClick={()=>void compare()}><ArrowLeftRight size={15}/>Comparar campos</button></div></div>
          {plan&&<><div className={styles.contentTitle}><h2>{comparisonName[plan.comparison.state]??plan.comparison.state}</h2><span className={styles.muted}>Comprobado {new Date(plan.comparison.observedAt).toLocaleString('es-ES')}</span></div>{plan.comparison.rows.some(row=>row.baseLocal!==undefined||row.baseRemote!==undefined)&&<p className={styles.muted}>{comparisonBasePersistence(store)==='persistent'?'Base privada guardada en este navegador. Solo avanzan los campos verificados.':'Base privada solo de esta sesión; almacenamiento persistente no disponible.'}</p>}{!plan.comparison.coverage.complete&&<div className={styles.banner}>Comparación parcial: {plan.comparison.coverage.unsupported.join(', ')}. No se reemplaza contenido que no puede preservarse.</div>}{plan.comparison.rows.map(row=><section key={row.field} className={styles.comparisonField}><div className={styles.contentTitle}><h3>{fieldName[row.field]}</h3><span className={styles.badge} data-status={row.state==='equal'?'done':'unknown'}>{comparisonName[row.state]??row.state}</span></div><div className={styles.threeWay}><section><h4>Base común</h4><pre>{row.baseLocal??'Sin base común verificada'}</pre></section><section><h4>Local</h4><pre>{row.local||'Sin contenido'}</pre></section><section><h4>{name}</h4><pre>{row.remote||'Sin contenido'}</pre></section></div></section>)}<details><summary>Ver representación de origen</summary><div className={styles.diff}><section><h3>Origen local</h3><pre>{plan.local.text}</pre></section><section><h3>{resource.representation}</h3><pre>{JSON.stringify(resource.fields,null,2)}</pre></section></div></details><div className={styles.actions}><button className="primary" disabled={busy||recovery} onClick={()=>void review()}>Revisar {direction==='publish'?'publicación':'importación'}</button><button onClick={exportCandidate}><Download size={15}/>Exportar candidato</button></div></>}
          <details style={{marginTop:20}}><summary>{provider==='jira'?'Historial accesible':'Versiones de la página'}</summary>{history.length?history.map(entry=><p className={styles.muted} key={entry.id}>{entry.version??entry.id} · {entry.summary} {entry.createdAt&&new Date(entry.createdAt).toLocaleString('es-ES')}</p>):<p className={styles.muted}>No se ha obtenido historial para este recurso.</p>}</details>
        </section>}
      </>}
    </>:<section><div className={styles.contentTitle}><h2>Configurar {name}</h2><button disabled={busy&&wizard===5} onClick={()=>void cancelWizard()}>Cancelar</button></div><ol className={styles.wizardSteps}>{['Preparar','Instancia','Autorizar','Ámbito','Comprobar','Resumen'].map((step,index)=><li key={step} aria-current={wizard===index?'step':undefined}>{index+1}. {step}</li>)}</ol>
      {wizard===0&&<div className={styles.guide}><p>Conectar no publica documentos ni crea incidencias. Primero comprobaremos el servicio y delimitarás el ámbito.</p><ol><li>Abre el conector de {name} con la instancia y las credenciales configuradas.</li><li>Carga su archivo de sesión local.</li><li>Elige el destino remoto y la carpeta del proyecto.</li><li>Comprueba el acceso y guarda la configuración.</li></ol><p className={styles.muted}>Las credenciales del proveedor permanecen en el sistema del conector. No se guardan en el proyecto.</p></div>}
      {wizard===1&&<div className={styles.form}><label>Dirección local del conector de {name}<input type="url" value={endpoint} onChange={e=>{setEndpoint(e.target.value);setChecked(false);generation.current++;if(draftClient)void draftClient.disconnect().catch(()=>undefined);setDraftClient(null);setCapabilities(null);setScopes([]);}}/></label><p>La modalidad Cloud o Data Center y la instancia se verificarán contra el perfil del conector. No se supone compatibilidad por introducir una dirección.</p></div>}
      {wizard===2&&<div className={styles.form}><label>Clave de sesión local<input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off"/></label><label>Cargar archivo de sesión de {name}<input type="file" aria-label={`Cargar archivo de sesión de ${name}`} onChange={e=>{const file=e.target.files?.[0];e.currentTarget.value='';if(!file)return;if(file.size>4096){setError('El archivo de sesión no tiene un tamaño válido.');return;}const version=generation.current;void file.text().then(value=>{if(version===generation.current)setToken(value.trim());}).catch(()=>setError('No se pudo leer el archivo de sesión.'));}}/></label><p className={styles.muted}>Se utiliza solo en memoria. No se envía a Jira o Confluence; autoriza esta web ante el conector local.</p>{draftClient?.connected&&<button disabled={busy} onClick={()=>setWizard(3)}>Continuar con conexión autorizada</button>}<div><button className="primary" disabled={busy||!token} onClick={()=>void authorize()}>{busy?'Autorizando…':`Autorizar conexión con ${name}`}</button></div></div>}
      {wizard===3&&<div className={styles.form}><p>Instancia verificada: <strong>{draftClient?.instance}</strong> · {capabilities?.deployment}</p><p>Cuenta verificada: <strong>{draftClient?.identity?.displayName}</strong> · ID {draftClient?.identity?.id}</p><label>{provider==='jira'?'Proyecto de Jira':'Espacio de Confluence'}<select value={scopeId} onChange={e=>{setScopeId(e.target.value);setChecked(false);}}>{scopes.map(scope=><option key={scope.id} value={scope.id}>{scope.name} · {scope.key??scope.id}</option>)}</select></label><label>Carpeta local incluida<select value={localRoot} onChange={e=>{setLocalRoot(e.target.value);setChecked(false);}}>{roots.map(root=><option key={root} value={root}>{root||'Raíz del proyecto'}</option>)}</select></label><p className={styles.muted}>La carpeta delimita candidatos. Seleccionarla no autoriza publicar todos sus archivos. Secretos, conversaciones y datos privados del conector quedan fuera del contenido sincronizado.</p>{!complete&&<p role="alert">El listado de destinos está incompleto; vuelve a comprobar antes de guardar.</p>}</div>}
      {wizard===4&&<><ul className={styles.verifications}>{checkRows.map(row=><li key={row.label}><strong>{row.label}</strong><span>{row.value}</span></li>)}</ul><button disabled={busy} className="primary" onClick={()=>void check()}><RefreshCw size={15}/>{busy?'Comprobando…':'Comprobar acceso y recurso'}</button></>}
      {wizard===5&&<><h3>Revisa la conexión</h3><dl className={styles.summaryList}><dt>Servicio</dt><dd>{name} · {capabilities?.deployment}</dd><dt>Instancia</dt><dd>{draftClient?.instance}</dd><dt>Cuenta</dt><dd>{draftClient?.identity?.displayName} · ID {draftClient?.identity?.id}</dd><dt>Destino</dt><dd>{scopes.find(scope=>scope.id===scopeId)?.name} · ID {scopeId}</dd><dt>Carpeta local</dt><dd>{localRoot||'Raíz del proyecto'}</dd><dt>Capacidades</dt><dd>Lectura y comparación {capabilities?.read?'verificadas':'no disponibles'}. Escritura remota {capabilities?.remoteUpdate?'admitida para el perfil':'bloqueada por las garantías del proveedor'}.</dd></dl><p className={styles.muted}>Guardar no vincula un documento ni establece una base común de comparación.</p>{store.mode!=='edit'&&<p>Activa Editor para guardar esta configuración en el proyecto.</p>}</>}
      <div className={styles.dialogFooter}>{wizard>0&&<button disabled={busy} onClick={()=>{setWizard(wizard-1);setChecked(wizard>=4?false:checked);}}>Atrás</button>}{wizard!==2&&wizard<5&&<button className="primary" disabled={busy||(wizard===3&&(!scopeId||!complete))||(wizard===4&&!checked)} onClick={()=>setWizard(wizard+1)}>Siguiente</button>}{wizard===5&&<button className="primary" disabled={!canConfigure||!checked} onClick={()=>void saveConnection()}>Guardar conexión</button>}</div>
    </section>}
    {pendingWarning&&<p role="alert" className={styles.banner}>{pendingWarning}{client&&<button disabled={busy} onClick={()=>void run(()=>discoverPending(client))}>Volver a consultar operaciones</button>}</p>}{pendingOperations.length>1&&<section><h2>Operaciones pendientes</h2>{pendingOperations.map(item=><button key={item.id} aria-pressed={operation?.id===item.id} disabled={busy} onClick={()=>setOperation(item)}>{item.resourceId} · {item.status} · {item.id}</button>)}</section>}
    {(recovery||operation)&&<div className={styles.banner} role="status" style={{margin:'20px 0'}}><strong>{operation?.status==='verified'?'Resultado verificado':operation?.status==='rejected'?'No aplicado':operation?.status==='partial'?'Resultado parcial':'Resultado sin confirmar'}</strong><p>{operation?.message??'La respuesta no llegó. Comprueba el resultado antes de repetir la operación.'}</p>{recovery&&<button disabled={busy} onClick={()=>void reconcile()}>Comprobar resultado</button>}</div>}
    {reviewOpen&&plan&&<Dialog title={plan.direction==='publish'?`Publicar en ${name}`:`Traer de ${name}`} wide onClose={()=>setReviewOpen(false)}><p>{plan.resource.instance} · {plan.resource.key??plan.resource.id} · versión {plan.resource.version}</p><p className={styles.filePath}>{plan.local.path}</p><p>Campos elegidos: {plan.fields.map(field=>fieldName[field]).join(', ')}.</p><div className={styles.diff}><section><h3>Antes · {plan.direction==='publish'?name:'Local'}</h3><pre>{plan.comparison.rows.filter(row=>plan.fields.includes(row.field)).map(row=>`${fieldName[row.field]}\n${plan.direction==='publish'?row.remote:row.local}`).join('\n\n')}</pre></section><section><h3>Después · {plan.direction==='publish'?name:'Local'}</h3><pre>{plan.comparison.rows.filter(row=>plan.fields.includes(row.field)).map(row=>`${fieldName[row.field]}\n${plan.direction==='publish'?row.local:row.remote}`).join('\n\n')}</pre></section></div>{plan.direction==='import'&&importChanges&&<section><h3>Archivos locales que cambiarán</h3>{importChanges.length?importChanges.map(change=><section key={change.path}><code>{change.path}</code><div className={styles.diff}><section><h4>Archivo actual</h4><pre>{change.before}</pre></section><section><h4>Archivo después de importar</h4><pre>{change.after}</pre></section></div></section>):<p>No hay cambios locales que aplicar.</p>}</section>}{blocking.length>0&&<div className={styles.banner} role="alert"><strong>Aplicación bloqueada</strong><ul>{blocking.map((reason,index)=><li key={index}>{reason}</li>)}</ul></div>}{plan.transportLoss.length>0&&<p>Transformaciones y límites: {plan.transportLoss.join('; ')}</p>}<p className={styles.muted}>Solo se usan los campos seleccionados. Los comentarios, reacciones, secretos y journals no se incluyen. Guardar localmente, commit y push siguen separados.</p><div className={styles.dialogFooter}><button onClick={()=>setReviewOpen(false)}>Volver a comparar</button><button onClick={exportCandidate}>Exportar candidato</button><button className="primary" disabled={!canWrite||blocking.length>0||(plan.direction==='import'&&!importChanges?.length)} onClick={()=>void apply()}>Confirmar {plan.direction==='publish'?'publicación':'importación'}</button></div></Dialog>}
    {unlinking&&currentBinding&&<Dialog title="Quitar vínculo" onClose={()=>setUnlinking(false)}><p>Se retirará la relación entre <strong>{currentBinding.local.path}</strong> y {currentBinding.resourceKey??currentBinding.resourceId}. Los archivos y el recurso remoto se conservarán.</p><div className={styles.dialogFooter}><button onClick={()=>setUnlinking(false)}>Cancelar</button><button disabled={!canWrite} onClick={()=>void run(async()=>{await unlinkIntegrationBinding(store,snapshot,provider,currentBinding.id);setUnlinking(false);setBindingId('');setResource(null);setPlan(null);await onRefresh();},true)}>Confirmar desvinculación</button></div></Dialog>}
  </main>;
}
