import { useEffect, useMemo, useState } from 'react';
import { X, MessageSquare, Plus, Check, CornerDownRight } from 'lucide-react';
import { addThread, mutateThread, loadThreads, getActor, saveActor, makeAnchor, makeFragmentAnchor, resolveAnchor, formatMessageDate, type Actor, type StoredThread, type ThreadAction } from '../services/comments';
import type { ProjectSnapshot, ProjectStore } from '../services/project-store';
import type { SourceSelection } from './SourceEditor';
import { Dialog } from './Dialog';
import styles from '../App.module.css';

const emojiChoices=['❤️','👀','🎉','🚀','💡','✅','🤔'];
const errorText=(error:unknown)=>error instanceof Error?error.message:String(error);
export function CommentsPanel({store,snapshot,path,source,selection,documentDirty,hidden,onClose,onRefresh,onDirty,onJump,onBusy,resetVersion}:{store:ProjectStore;snapshot:ProjectSnapshot;path:string;source:string;selection:SourceSelection|null;documentDirty:boolean;hidden:boolean;onClose:()=>void;onRefresh:()=>Promise<void>;onDirty:(dirty:boolean)=>void;onJump:(line:number)=>void;onBusy:(busy:boolean)=>void;resetVersion:number}) {
  const loaded=useMemo(()=>loadThreads(snapshot),[snapshot]);const threads=loaded.threads.filter(s=>s.thread.anchor.path===path);
  const [selectedId,setSelectedId]=useState(''),[draft,setDraft]=useState(''),[reply,setReply]=useState(''),[editing,setEditing]=useState(''),[editedText,setEditedText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[actor,setActor]=useState<Actor>(()=>getActor()),[actorName,setActorName]=useState(actor.name),[emojiFor,setEmojiFor]=useState(''),[lineStart,setLineStart]=useState(1),[lineEnd,setLineEnd]=useState(1),[manualSelection,setManualSelection]=useState<SourceSelection|null>(null),[pending,setPending]=useState<(()=>void)|null>(null),[reanchoring,setReanchoring]=useState(false);
  const selected=threads.find(s=>s.thread.id===selectedId)??threads[0]; const activeSelection=manualSelection;
  const dirty=!!(draft||reply||editing&&editedText!==selected?.thread.messages.find(m=>m.id===editing)?.text);
  useEffect(()=>onDirty(dirty),[dirty,onDirty]);
  useEffect(()=>{setDraft('');setReply('');setEditing('');setEditedText('');setManualSelection(null);setError('');},[path,resetVersion]);
  useEffect(()=>{if(selection)setManualSelection(selection);},[selection]);
  const editable=store.mode==='edit'&&!store.recoveryPending;
  async function run(action:()=>Promise<void>) {setBusy(true);onBusy(true);setError('');try{await action();await onRefresh();}catch(e){setError(errorText(e));}finally{setBusy(false);onBusy(false);}}
  function requireActor(){if(!actor.name)throw new Error('Indica el nombre que aparecerá en tus comentarios.');return actor;}
  function mutate(stored:StoredThread,action:ThreadAction,after?:()=>void){void run(async()=>{await mutateThread(store,stored,requireActor(),action);after?.();});}
  function guard(action:()=>void){if(busy)return;if(dirty){setPending(()=>action);return;}action();}
  function getSelectedAnchor(){if(!activeSelection)throw new Error('Selecciona un fragmento o un rango de líneas.');if(documentDirty)throw new Error('Guarda primero el documento y vuelve a seleccionar el fragmento. El comentario se conserva.');return makeFragmentAnchor(path,source,snapshot.revisions[path],activeSelection.start,activeSelection.end);}
  function chooseLines(){try{const anchor=makeAnchor(path,source,snapshot.revisions[path],lineStart,lineEnd);const start=source.split('\n').slice(0,lineStart-1).join('\n').length+(lineStart>1?1:0);setManualSelection({start,end:start+anchor.quote.length,quote:anchor.quote});setError('');}catch(e){setError(errorText(e));}}
  return <aside className={styles.comments} hidden={hidden} aria-label="Comentarios del documento">
    <div className={styles.commentsHeader}><h2>Comentarios <span className={styles.muted}>{threads.length}</span></h2><button className="iconButton" aria-label="Cerrar comentarios" onClick={onClose}><X size={16}/></button></div>
    {!editable&&<p className={styles.muted}>Activa Editor para escribir y reaccionar.</p>}
    {editable&&!actor.name&&<div className={styles.reply}><label>Tu nombre<input value={actorName} onChange={e=>setActorName(e.target.value)} maxLength={80}/></label><button onClick={()=>{try{const next={...actor,name:actorName.trim()};saveActor(next);setActor(next);setError('');}catch(e){setError(errorText(e));}}}>Usar este nombre</button><p className={styles.muted}>Identidad local declarada; se incluirá en los archivos de comentarios.</p></div>}
    {loaded.errors.length>0&&<p role="alert" className={styles.muted}>Hay {loaded.errors.length} archivos de comentarios que no se pudieron leer. Se conservan sin cambios.</p>}
    {error&&<div role="alert" className={`${styles.banner} ${styles.bannerError}`} style={{margin:'12px 0'}}>{error}<button onClick={()=>void onRefresh()}>Releer conversación</button></div>}
    <div className={styles.threadTabs}>{threads.map((stored,i)=><button key={stored.thread.id} aria-pressed={selected?.thread.id===stored.thread.id} onClick={()=>guard(()=>{setSelectedId(stored.thread.id);setReply('');setEditing('');setDraft('');setError('');})}>H{i+1} · {stored.thread.status==='resolved'?'Resuelto':'Abierto'}</button>)}</div>
    {selected&&<>
      {(()=>{const resolution=resolveAnchor(selected.thread.anchor,snapshot.files[path],snapshot.revisions[path]);const labels={exact:'Fragmento localizado',moved:'Fragmento reubicado en esta vista',ambiguous:'Fragmento ambiguo',outdated:'El fragmento ya no está',missing:'Documento no disponible'};return <><p className={styles.muted}>{labels[resolution.state]}{resolution.startLine?` · línea ${resolution.startLine}`:''}</p><blockquote className={styles.quote}>{selected.thread.anchor.quote}</blockquote><div className={styles.actions}>{resolution.startLine&&<button onClick={()=>onJump(resolution.startLine!)}><CornerDownRight size={13}/>Ir al fragmento</button>}{editable&&<button disabled={busy} onClick={()=>setReanchoring(!reanchoring)}>Reanclar</button>}</div></>;})()}
      {selected.thread.messages.map(message=>{
        const kinds=['like','dislike',...new Set(message.reactions.map(r=>r.kind).filter(k=>!['like','dislike','approve','disapprove'].includes(k)))];
        return <section className={styles.message} key={message.id} aria-label={`Mensaje de ${message.author.name}`}>
          <div className={styles.messageMeta}><strong>{message.author.id===actor.id?'Tú':message.author.name}</strong><time dateTime={message.createdAt} title={new Date(message.createdAt).toLocaleString('es-ES',{timeZone:'Europe/Madrid'})}>{formatMessageDate(message.createdAt)}</time>{message.editedAt&&<small title={`Editado ${new Date(message.editedAt).toLocaleString('es-ES',{timeZone:'Europe/Madrid'})}`}>editado</small>}</div>
          {editing===message.id?<div className={styles.reply}><label>Editar tu respuesta<textarea value={editedText} onChange={e=>setEditedText(e.target.value)} disabled={busy}/></label><div className={styles.actions}><button className="primary" disabled={busy||!editedText.trim()} onClick={()=>mutate(selected,{type:'edit',messageId:message.id,text:editedText},()=>{setEditing('');setEditedText('');})}>Guardar cambios</button><button disabled={busy} onClick={()=>guard(()=>{setEditing('');setEditedText('');})}>Cancelar</button></div></div>:<p>{message.text}</p>}
          <div className={styles.reactions}>{kinds.map(kind=>{const reactions=message.reactions.filter(r=>r.kind===kind),own=reactions.some(r=>r.actorId===actor.id),emoji=kind==='like'?'👍':kind==='dislike'?'👎':kind;const participants=reactions.map(r=>r.actorName??selected.thread.messages.find(m=>m.author.id===r.actorId)?.author.name??(r.actorId===actor.id?actor.name:'Participante')).join(', ');return <button key={kind} aria-label={`${emoji}: ${reactions.length} reacciones`} aria-pressed={own} title={participants||'Sin reacciones'} disabled={!editable||busy||!actor.name} onClick={()=>mutate(selected,{type:'react',messageId:message.id,kind})}>{emoji} {reactions.length}</button>})}<button aria-label={`Añadir emoji al mensaje de ${message.author.name}`} disabled={!editable||busy||!actor.name} onClick={()=>setEmojiFor(emojiFor===message.id?'':message.id)}><Plus size={12}/></button></div>
          {emojiFor===message.id&&<div className={styles.reactions} role="group" aria-label="Elegir emoji">{emojiChoices.map(kind=><button key={kind} aria-label={`Reaccionar con ${kind}`} onClick={()=>{setEmojiFor('');mutate(selected,{type:'react',messageId:message.id,kind});}}>{kind}</button>)}</div>}
          {editable&&message.author.id===actor.id&&editing!==message.id&&<button className="link" disabled={busy} onClick={()=>guard(()=>{setEditing(message.id);setEditedText(message.text);})}>Editar</button>}
        </section>;
      })}
      <div className={styles.commentActions}><button disabled={!editable||busy||!actor.name} onClick={()=>mutate(selected,{type:selected.thread.status==='open'?'resolve':'reopen'})}><Check size={13}/>{selected.thread.status==='open'?'Resolver':'Reabrir'}</button>{selected.thread.status==='resolved'&&<span className={styles.badge} data-status="done">Resuelto</span>}</div>
      {editable&&<div className={styles.reply}><label>Responder<textarea placeholder="Escribe una respuesta…" value={reply} onChange={e=>setReply(e.target.value)} disabled={busy}/></label><button className="primary" disabled={busy||!reply.trim()||!actor.name} onClick={()=>mutate(selected,{type:'reply',text:reply},()=>setReply(''))}>Guardar respuesta</button></div>}
    </>}
    {!selected&&<div className={styles.muted}><MessageSquare size={20}/><p>Este documento aún no tiene comentarios.</p></div>}
    {editable&&<details className={styles.reply} open={!!activeSelection||reanchoring}><summary>{reanchoring?'Elegir el nuevo fragmento':'Comentar un fragmento'}</summary><p className={styles.muted}>Selecciona texto en el documento o indica las líneas físicas del Markdown.</p><div className={styles.lineSelect}><label>Desde<input aria-label="Línea inicial" type="number" min="1" value={lineStart} onChange={e=>setLineStart(Number(e.target.value))}/></label><label>Hasta<input aria-label="Línea final" type="number" min={lineStart} value={lineEnd} onChange={e=>setLineEnd(Number(e.target.value))}/></label><button onClick={chooseLines}>Seleccionar</button></div>
      {activeSelection&&<blockquote className={styles.quote}>{activeSelection.quote}</blockquote>}
      {reanchoring&&selected?<><p className={styles.muted}>La cita original se conservará en el historial del hilo.</p><button disabled={!activeSelection||documentDirty||busy} onClick={()=>{try{const anchor=getSelectedAnchor();mutate(selected,{type:'reanchor',anchor},()=>setReanchoring(false));}catch(e){setError(errorText(e));}}}>Confirmar nuevo fragmento</button><button onClick={()=>setReanchoring(false)}>Cancelar reanclaje</button></>:<><label>Nuevo comentario<textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Escribe tu comentario…" disabled={busy}/></label>{documentDirty&&<p className={styles.muted}>Guarda el documento y vuelve a seleccionar el fragmento antes de comentar.</p>}<button className="primary" disabled={busy||!draft.trim()||!activeSelection||documentDirty||!actor.name} onClick={()=>void run(async()=>{const anchor=getSelectedAnchor();const thread=await addThread(store,anchor,requireActor(),draft);setSelectedId(thread.id);setDraft('');setManualSelection(null);})}>Guardar comentario</button></>}
    </details>}
    {dirty&&<p className={styles.muted}>Las respuestas sin guardar solo permanecen en esta pestaña. Guarda o copia el texto antes de recargar.</p>}
    {busy&&<p role="status" className={styles.muted}>Guardando conversación…</p>}
    {pending&&<Dialog title="Hay una respuesta sin guardar" onClose={()=>setPending(null)}><p>Conserva el borrador o descártalo antes de continuar.</p><div className={styles.dialogFooter}><button onClick={()=>setPending(null)}>Seguir aquí</button><button onClick={()=>{const action=pending;setPending(null);setDraft('');setReply('');setEditing('');setEditedText('');action();}}>Descartar borrador y continuar</button></div></Dialog>}
  </aside>;
}
