import { useEffect, useRef, useState } from 'react';
import { GitBranch, GitCommitHorizontal, Upload, RefreshCw, Plug, Unplug, Download, CircleCheck } from 'lucide-react';
import { GitClient, ConnectorError, definitiveRejection, type GitRepository, type GitPlan, type GitOperation, type GitBranch as Branch, type MutationContext } from '../services/git-client';
import type { ProjectStore } from '../services/project-store';
import { Dialog } from './Dialog';
import styles from '../App.module.css';

type Phase='idle'|'checking'|'permission'|'linking'|'connected'|'disconnected'|'update'|'gitmissing'|'attention';
const label:Record<Phase,string>={idle:'No conectado',checking:'Comprobando…',permission:'Permiso pendiente',linking:'Vinculando proyecto…',connected:'Conectado',disconnected:'Conexión perdida',update:'Actualización requerida',gitmissing:'Git no disponible',attention:'Necesita atención'};
const explain=(error:unknown)=>error instanceof Error?error.message:String(error);
export function GitPanel({store,hidden,context,onStatus,onBusy,onRefresh}:{store:ProjectStore;hidden:boolean;context:MutationContext;onStatus:(state:string)=>void;onBusy:(busy:boolean)=>void;onRefresh:()=>Promise<void>}) {
  const [client,setClient]=useState<GitClient|null>(null),[phase,setPhase]=useState<Phase>('idle'),[endpoint,setEndpoint]=useState('http://127.0.0.1:43120'),[token,setToken]=useState(''),[trusted,setTrusted]=useState(false),[repository,setRepository]=useState<GitRepository|null>(null),[branches,setBranches]=useState<Branch[]>([]),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(''),[branch,setBranch]=useState(''),[remote,setRemote]=useState(''),[plan,setPlan]=useState<GitPlan|null>(null),[operation,setOperation]=useState<GitOperation|null>(null),[lostPlan,setLostPlan]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[hint,setHint]=useState(''),[guide,setGuide]=useState(false);
  const contextRef=useRef(context);contextRef.current=context;
  const generation=useRef(0);
  useEffect(()=>onStatus(label[phase]),[phase,onStatus]);
  useEffect(()=>{setClient(null);setPhase('idle');setRepository(null);setPlan(null);setOperation(null);setLostPlan('');setSelected([]);setToken('');setTrusted(false);generation.current++;},[store]);
  const recovery=!!lostPlan||operation?.status==='uncertain'||operation?.status==='running';
  const mutationContext=()=>({...contextRef.current,recoveryPending:contextRef.current.recoveryPending||recovery});
  function fail(error:unknown){setError(explain(error));const code=error instanceof ConnectorError?error.code:'';if(code==='unreachable')setPhase(client?.connected?'disconnected':'idle');else if(/GIT_NOT|GIT_MISSING|gitmissing/.test(code))setPhase('gitmissing');else if(/AUTH|ORIGIN|TRUST|permission/.test(code))setPhase('permission');else if(/VERSION|PROTOCOL/.test(code))setPhase('update');else setPhase(client?.connected?'attention':'idle');}
  async function run(action:()=>Promise<void>,mutation=false){setBusy(true);setError('');setHint('');if(mutation)onBusy(true);try{await action();}catch(e){fail(e);}finally{setBusy(false);if(mutation)onBusy(false);}}
  async function reload(active=client){if(!active)return;const [repo,list]=await Promise.all([active.repository(),active.branches()]);setRepository(repo);setBranches(list.branches);setBranch(repo.branch??'');setRemote(current=>repo.remotes.some(r=>r.name===current)?current:repo.remotes[0]?.name??'');setSelected(paths=>paths.filter(path=>repo.changes.some(c=>c.path===path)));setPhase('connected');}
  async function connect(){await run(async()=>{const current=++generation.current;const active=new GitClient(endpoint);setPhase('checking');await active.health();if(current!==generation.current)return;setPhase('linking');const repo=await active.connect(store,token,trusted);if(current!==generation.current){await active.disconnect();return;}setClient(active);setRepository(repo);setToken('');await reload(active);const pending=await active.pendingOperations();setOperation(pending.operations.find(op=>op.status==='running'||op.status==='uncertain')??null);await onRefresh();},true);}
  async function disconnect(){await run(async()=>{generation.current++;await client?.disconnect();setClient(null);setRepository(null);setPhase('idle');setToken('');setPlan(null);});}
  async function review(kind:'commit'|'branch'|'push'){if(!client)return;await run(async()=>{setOperation(null);const context=mutationContext();setPlan(kind==='commit'?await client.planCommit(selected,message,context):kind==='branch'?await client.planBranch(branch,context):await client.planPush(remote,branch,context));});}
  async function execute(){if(!client||!plan)return;const reviewed=plan;setPlan(null);await run(async()=>{try{const result=await client.execute(reviewed.id,mutationContext());setOperation(result);setLostPlan('');if(result.status==='verified'){await reload();await onRefresh();if(reviewed.kind==='commit'){setMessage('');setSelected([]);}}else setPhase('attention');}catch(e){setLostPlan(definitiveRejection(e)?'':reviewed.id);setPhase('attention');throw e;}},true);}
  async function reconcile(){if(!client)return;await run(async()=>{if(operation){const result=await client.reconcile(operation.id);setOperation(result);if(result.status==='verified'){setLostPlan('');await reload();await onRefresh();}}else if(lostPlan){const recorded=await client.operationByPlan(lostPlan);if(!recorded)throw new Error('El conector todavía no tiene un resultado para este plan. La operación sigue pendiente de comprobación.');setOperation(recorded);setLostPlan('');if(recorded.status==='verified'){await reload();await onRefresh();}}},true);}
  const blocked=!!repository?.conflicts.length||!!repository?.operationInProgress.length||store.mode!=='edit'||busy||recovery||context.saving||context.recoveryPending||context.drafts>0||!client?.connected;
  const changeForm=(action:()=>void)=>{setPlan(null);action();};
  return <main hidden={hidden} className={`${styles.content} ${styles.connectionPage}`}>
    <div className={styles.contentTitle}><div><h1>Conexión con Git</h1><p className={styles.muted}>Ramas, commits y push con el Git de tu equipo.</p></div><span className={styles.badge} data-status={phase==='connected'?'done':['idle','checking','linking'].includes(phase)?'backlog':'unknown'}>{label[phase]}</span></div>
    {error&&<div role="alert" className={`${styles.banner} ${styles.bannerError}`} style={{margin:'16px 0'}}>{error}</div>}
    {hint&&<p role="status" className={`${styles.banner} ${styles.bannerInfo}`} style={{margin:'16px 0'}}>{hint}</p>}
    {(!client||!repository)&&<><p>La lectura, edición y los comentarios funcionan con el permiso de carpeta. El conector añade las operaciones Git de este repositorio.</p><div className={styles.actions}><button onClick={()=>setGuide(true)}><Download size={16}/>Instalar conector Git</button><button disabled={busy} onClick={()=>void run(async()=>{setPhase('checking');const probe=new GitClient(endpoint);const health=await probe.health();setPhase('permission');setHint(`Conector ${health.version} disponible. Introduce la clave de sesión y vincula esta carpeta.`);})}>Ya lo tengo / Comprobar</button></div>
      <form className={styles.form} onSubmit={e=>{e.preventDefault();void connect();}}><label>Dirección local del conector<input type="url" value={endpoint} onChange={e=>setEndpoint(e.target.value)} disabled={busy} spellCheck={false}/></label><label>Clave de sesión del conector<input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off" spellCheck={false} disabled={busy}/></label><label>Cargar archivo de sesión<input type="file" aria-label="Cargar archivo de sesión" disabled={busy} onChange={event=>{const file=event.currentTarget.files?.[0];event.currentTarget.value='';if(!file)return;if(file.size>4096){setError('El archivo de sesión no tiene un tamaño válido.');return;}void file.text().then(value=>{setToken(value.trim());setError('');}).catch(()=>setError('No se pudo leer el archivo de sesión.'));}}/></label><p className={styles.muted}>La clave permanece solo en esta pestaña. La autenticación del remoto sigue a cargo de Git y el sistema.</p><label className={styles.checkboxRow}><input type="checkbox" checked={trusted} onChange={e=>setTrusted(e.target.checked)} disabled={busy}/>Confío en los hooks, filtros y gestores de credenciales de este repositorio.</label>{store.mode!=='edit'&&<p className={styles.muted}>Activa Editor para comprobar que ambas aplicaciones abren la misma carpeta. Se escribirá y retirará un marcador temporal.</p>}<div className={styles.actions}><button className="primary" disabled={busy||!token||!trusted||store.mode!=='edit'} type="submit"><Plug size={16}/>{busy?'Comprobando…':'Conectar y vincular proyecto'}</button>{busy&&phase==='checking'&&<button type="button" onClick={()=>{generation.current++;setPhase('idle');setBusy(false);onBusy(false);}}>Cancelar comprobación</button>}</div></form>
    </>}
    {repository&&client&&<><section className={styles.listItem}><div className={styles.contentTitle}><div><h2>{repository.rootName}</h2><p className={styles.muted}>Rama {repository.branch??'HEAD separado'} · {repository.head?.slice(0,12)??'Sin commits'}</p></div><div className={styles.actions}><button disabled={busy} onClick={()=>void run(()=>reload())}><RefreshCw size={15}/>Comprobar</button><button disabled={busy||recovery} onClick={()=>void disconnect()}><Unplug size={15}/>Desconectar</button></div></div>{repository.conflicts.length>0&&<p role="alert">Hay conflictos: {repository.conflicts.join(', ')}. Resuélvelos con Git y vuelve a comprobar.</p>}{repository.operationInProgress.length>0&&<p role="alert">Git tiene una operación pendiente: {repository.operationInProgress.join(', ')}.</p>}</section>
      {recovery&&<div className={styles.banner} role="alert" style={{margin:'16px 0'}}><strong>Resultado pendiente de comprobación</strong><p>La operación puede haberse aplicado. Comprueba el resultado antes de repetirla.</p><button disabled={busy} onClick={()=>void reconcile()}>Comprobar resultado</button>{lostPlan&&<p className={styles.muted}>Plan {lostPlan}</p>}</div>}
      {operation&&<div role="status" className={`${styles.banner} ${operation.status==='verified'?styles.bannerSuccess:''}`} style={{margin:'16px 0'}}><strong>{operation.status==='verified'?'Resultado verificado':operation.status==='rejected'?'Operación rechazada':operation.status==='running'?'Operación en curso':'Resultado sin confirmar'}</strong>{operation.head&&<p>Commit {operation.head}</p>}{operation.remoteSha&&<p>Revisión remota {operation.remoteSha}</p>}{operation.error&&<p>{operation.error.message}</p>}{operation.warning&&<p>{operation.warning}</p>}</div>}
      <h2>Cambios locales</h2><p className={styles.muted}>Selecciona los archivos que formarán el commit. Guardar documentos y crear un commit son acciones separadas.</p>{repository.staged.length>0&&<div className={styles.banner} style={{margin:'12px 0'}}>Hay {repository.staged.length} archivos en el índice de Git. Confirma o retira esos cambios desde tu cliente Git antes de crear otro commit aquí.</div>}<div className={styles.list}>{repository.changes.map(change=><label className={`${styles.listItem} ${styles.checkboxRow}`} key={change.path}><input type="checkbox" checked={selected.includes(change.path)} disabled={blocked} onChange={e=>changeForm(()=>setSelected(paths=>e.target.checked?[...paths,change.path]:paths.filter(p=>p!==change.path)))}/><code>{change.index}{change.workingTree}</code><span>{change.originalPath?`${change.originalPath} → `:''}{change.path}</span></label>)}</div>{!repository.changes.length&&<p className={styles.muted}><CircleCheck size={15}/> El árbol de trabajo no tiene cambios.</p>}
      <div className={styles.form}><label>Mensaje del commit<textarea value={message} onChange={e=>changeForm(()=>setMessage(e.target.value))} disabled={blocked} placeholder="Describe el cambio"/></label><div><button disabled={blocked||!selected.length||!message.trim()||repository.staged.length>0} onClick={()=>void review('commit')}><GitCommitHorizontal size={16}/>Revisar commit</button></div></div>
      <h2>Rama y publicación</h2><div className={styles.form}><label>Rama<select value={branch} onChange={e=>changeForm(()=>setBranch(e.target.value))} disabled={blocked}>{branches.map(item=><option key={item.name} value={item.name}>{item.name}{item.current?' · actual':''}{item.worktree&&!item.current?' · en otro checkout':''}</option>)}</select></label><div><button disabled={blocked||!branch||branch===repository.branch} onClick={()=>void review('branch')}><GitBranch size={16}/>Revisar cambio de rama</button></div><label>Remoto<select value={remote} onChange={e=>changeForm(()=>setRemote(e.target.value))} disabled={blocked}>{repository.remotes.map(item=><option key={item.name} value={item.name}>{item.name} · {item.url}</option>)}</select></label><div><button disabled={blocked||!branch||!remote} onClick={()=>void review('push')}><Upload size={16}/>Revisar push</button></div></div>{store.mode!=='edit'&&<p className={styles.muted}>Las consultas siguen disponibles. Activa Editor para preparar operaciones Git.</p>}
    </>}
    {plan&&<Dialog title={plan.summary} wide onClose={()=>setPlan(null)}><p className={styles.muted}>Revisión {plan.head?.slice(0,12)??'inicial'} · válido hasta {new Date(plan.expiresAt).toLocaleTimeString('es-ES')}</p>{plan.remoteUrl&&<p><strong>Destino:</strong> {plan.remoteUrl} · {plan.branch}</p>}{plan.kind==='push'&&<><h3>Todos los commits salientes ({plan.commits?.length??0})</h3><p className={styles.muted}>Incluye los commits creados fuera de esta interfaz.</p>{plan.commits?.map(commit=><details key={commit.sha}><summary>{commit.sha.slice(0,12)} · {commit.subject}</summary>{commit.files.map((file,i)=><section key={`${file.path}-${i}`}><code>{file.status} {file.path}</code><pre className={styles.rawText}>{file.diff}</pre></section>)}</details>)}</>}{plan.files.map((file,i)=><details key={`${file.path}-${i}`} open><summary>{file.status} · {file.path}</summary><pre className={styles.rawText}>{file.diff||'Sin diferencia textual disponible.'}</pre></details>)}<div className={styles.dialogFooter}><button onClick={()=>setPlan(null)}>Cancelar</button><button className="primary" disabled={blocked} onClick={()=>void execute()}>Confirmar {plan.kind==='commit'?'commit local':plan.kind==='push'?'push al remoto':'cambio de rama'}</button></div></Dialog>}
    {guide&&<Dialog title="Instalar el conector Git" onClose={()=>setGuide(false)}><p>El paquete de BMAD Project UI incluye el runtime de Node. Git debe estar instalado en el equipo.</p><ol><li>Abre el paquete correspondiente a macOS, Windows o Linux.</li><li>Ejecuta <code>install.command</code>, <code>install.cmd</code> o <code>install.sh</code>. La instalación no inicia servicios automáticamente.</li><li>Abre el lanzador para el repositorio y autoriza la dirección de esta web.</li><li>Vuelve aquí, carga el archivo de sesión del conector y vincula la carpeta.</li></ol><p className={styles.muted}>Los paquetes privados y sus comprobaciones SHA-256 están disponibles como artefactos de la compilación en GitHub Actions. Descarga el que corresponda a tu sistema.</p><p><a href="https://github.com/enzovalley9/bmad-project-ui/actions" target="_blank" rel="noopener noreferrer">Abrir artefactos privados en GitHub</a></p><details><summary>Inicio desde el código del proyecto</summary><pre className={styles.rawText}>npm run connector:git -- --repo /ruta/al/proyecto --origin {window.location.origin} --token-file /ruta/privada/clave-de-sesion</pre></details><button onClick={()=>setGuide(false)}>Ya lo tengo / Conectar</button></Dialog>}
  </main>;
}
