import { useState, type CSSProperties } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {resolveDocumentLink} from './DocumentReader';
import { Inbox, FileQuestion, ListChecks } from 'lucide-react';
import { planWorkItemEdit, visibleWorkItems, type WorkItem, type ProjectIndex, type FileChange } from '../../../../packages/domain/src/index';
import type { ProjectSnapshot, ProjectStore } from '../services/project-store';
import { Dialog } from './Dialog';
import styles from '../App.module.css';

const labels:Record<string,string>={backlog:'Backlog','ready-for-dev':'Preparadas','in-progress':'En progreso',review:'En revisión',done:'Hechas',todo:'Pendientes',draft:'Borrador',blocked:'Bloqueadas',built:'Build terminado',cancelled:'Descartadas',open:'Abiertas',optional:'Opcional'};
export const statusLabel=(status:string)=>labels[status]??status;
export function StoryBoard({index,onOpen}:{index:ProjectIndex;onOpen:(item:WorkItem)=>void}) {
  const [query,setQuery]=useState(''),[epic,setEpic]=useState(''),[kind,setKind]=useState('story');
  const projected=visibleWorkItems(index); const all=projected.filter(item=>item.kind===kind);const epics=projected.filter(item=>item.kind==='epic');
  const items=all.filter(item=>(!epic||item.epicId===epic)&&`${item.title} ${item.nativeId??item.id}`.toLowerCase().includes(query.toLowerCase()));
  const statuses=all.reduce<string[]>((values,item)=>{for(const status of item.status?.allowed??[])if(!values.includes(status))values.push(status);return values;},[]);
  const known=items.filter(item=>item.status?.valid&&statuses.includes(item.status.raw));const unknown=items.filter(item=>!known.includes(item));
  const card=(item:WorkItem)=><button className={styles.card} key={item.id} onClick={()=>onOpen(item)}><span className={styles.cardTitle}>{item.title}</span><span className={styles.cardId}>{item.nativeId??item.id}</span><span className={styles.cardEpic}>{item.epicId?`Épica ${epics.find(e=>e.id===item.epicId||e.nativeId===item.epicId)?.nativeId??item.epicId} · ${epics.find(e=>e.id===item.epicId||e.nativeId===item.epicId)?.title??'Relación declarada'}`:'Sin épica declarada'}</span></button>;
  return <div className={styles.content}><div className={styles.contentTitle}><div><h1>Historias</h1><p className={styles.muted}>{items.length} elementos · estado leído de los archivos</p></div><div className={styles.actions}><input aria-label="Buscar historia" placeholder="Buscar historia…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Tipo de trabajo" value={kind} onChange={e=>setKind(e.target.value)}><option value="story">Historias</option><option value="build">Builds</option><option value="action">Compromisos</option><option value="retrospective">Retrospectivas</option></select><select aria-label="Filtrar por épica" value={epic} onChange={e=>setEpic(e.target.value)}><option value="">Todas las épicas</option>{epics.map(e=><option key={e.id} value={e.nativeId??e.id}>{e.nativeId??e.id} · {e.title}</option>)}</select></div></div>
    {statuses.length>0&&<div className={styles.board} style={{'--board-columns':Math.min(statuses.length,5)} as CSSProperties}>{statuses.map(status=><section className={styles.column} key={status} aria-label={statusLabel(status)}><div className={styles.columnHeader}>{statusLabel(status)}<span>{known.filter(i=>i.status?.raw===status).length}</span></div>{known.filter(i=>i.status?.raw===status).map(card)}{!known.some(i=>i.status?.raw===status)&&<p className={styles.emptyColumn}>No hay elementos en {statusLabel(status).toLowerCase()}.</p>}</section>)}</div>}
    {unknown.length>0&&<section className={styles.unclassified}><h2>Sin clasificar</h2><p className={styles.muted}>Se conserva el valor original; no se asigna un estado por aproximación.</p><div>{unknown.map(item=><div key={item.id}><span className={styles.badge} data-status="unknown">{item.status?.raw??'Sin estado declarado'}</span>{card(item)}</div>)}</div></section>}
    {!items.length&&<div className={styles.empty}><Inbox size={30}/><h2>No hay {kind==='story'?'historias':'elementos'} disponibles</h2><p>Revisa los filtros o consulta los documentos y el diagnóstico del proyecto.</p></div>}
  </div>;
}
export function StoryDescription({text,path,onNavigate}:{text:string;path:string;onNavigate:(path:string)=>void}){return <div className={styles.storyDescription}><ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml components={{img:()=>null,a:({href,children})=>{if(href&&/^https?:\/\//i.test(href))return <a href={href} target="_blank" rel="noopener noreferrer">{children}</a>;const local=href?resolveDocumentLink(path,href):null;return local?<button className="link" onClick={()=>onNavigate(local)}>{children}</button>:<span>{children}</span>;},input:({node:_node,...props})=><input {...props} disabled aria-label="Criterio del documento"/>,table:({node:_node,...props})=><div className={styles.tableScroll}><table {...props}/></div>}}>{text}</ReactMarkdown></div>;}
export function StoryDialog({item,snapshot,store,onClose,onNavigate,onRefresh,onBusy}:{item:WorkItem;snapshot:ProjectSnapshot;store:ProjectStore;onClose:()=>void;onNavigate:(path:string)=>void;onRefresh:()=>Promise<void>;onBusy:(value:boolean)=>void}) {
  const [editing,setEditing]=useState(false),[field,setField]=useState<'title'|'description'|'status'>(item.editable.title?'title':item.editable.description?'description':'status'),[value,setValue]=useState(item.editable.title?item.title:item.editable.description?item.description??'':item.status?.raw??''),[changes,setChanges]=useState<FileChange[]|null>(null),[warnings,setWarnings]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[exitAction,setExitAction]=useState<(()=>void)|null>(null);
  const original=field==='title'?item.title:field==='description'?item.description??'':item.status?.raw??'';
  function requestExit(action:()=>void){if(busy)return;if(changes||editing&&value!==original){setExitAction(()=>action);return;}action();}
  const epic=snapshot.index.workItems.find(e=>e.id===item.epicId||e.nativeId===item.epicId);
  function plan(nextField:'title'|'description'|'status'|'checklist',nextValue:string|boolean,checklistId?:string){try{const result=planWorkItemEdit(snapshot.index,snapshot.files,{id:item.id,field:nextField,value:nextValue,checklistId});setChanges(result.changes);setWarnings(result.warnings);setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}}
  async function save(){if(!changes||store.recoveryPending)return;setBusy(true);onBusy(true);try{await store.applyChanges(changes);await onRefresh();setChanges(null);setEditing(false);onClose();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);onBusy(false);}}
  return <Dialog title={item.nativeId??item.id} onClose={()=>requestExit(onClose)} wide={!!changes}>
    {error&&<div role="alert" className={`${styles.banner} ${styles.bannerError}`}>{error}</div>}
    {changes?<><h2>Revisar cambios antes de guardar</h2>{changes.map(change=><section key={change.path}><code>{change.path}</code><div className={styles.diff}><section><h3>Archivo actual</h3><pre>{change.before}</pre></section><section><h3>Después de guardar</h3><pre>{change.after}</pre></section></div></section>)}{warnings.map(w=><p key={w} className={styles.muted}>{w}</p>)}<div className={styles.dialogFooter}><button disabled={busy} onClick={()=>setChanges(null)}>Volver</button><button className="primary" disabled={busy||!changes.length||store.recoveryPending} onClick={()=>void save()}>{busy?'Guardando…':'Confirmar y guardar'}</button></div></>:<>
      <span className={styles.badge} data-status={item.status?.valid?item.status.raw:'unknown'}>{item.status?statusLabel(item.status.raw):'Sin estado declarado'}</span><h1 className={styles.storyTitle}>{item.title}</h1>
      {item.epicId&&<details className={styles.storyEpic}><summary>Épica {epic?.nativeId??item.epicId} · {epic?.title??'Relación declarada'}</summary>{epic?.description&&<p>{epic.description}</p>}</details>}
      {item.description&&<section><h2>Descripción</h2><StoryDescription text={item.description} path={item.fields.description?.source.path??item.source.path} onNavigate={path=>requestExit(()=>onNavigate(path))}/></section>}
      {item.checklist.length>0&&<section><h2><ListChecks size={17}/> Tareas y criterios</h2>{item.checklist.map(task=><label key={task.id} className={styles.checkboxRow} style={{marginLeft:task.depth*12}}><input type="checkbox" checked={task.checked} disabled={store.mode!=='edit'||store.recoveryPending} onChange={e=>plan('checklist',e.target.checked,task.id)}/>{task.text}</label>)}</section>}
      {item.relatedStatuses.map((status,i)=><p className={styles.muted} key={i}>{status.role}: <strong>{status.raw}</strong> · {status.source.path}</p>)}
      {item.warnings.map(w=><p key={w} className={styles.muted}>{w}</p>)}
      <details className={styles.provenance}><summary>Procedencia</summary><p>Contenido</p><code>{item.source.path} · líneas {item.source.lineStart}–{item.source.lineEnd}</code>{item.status&&<><p>Estado: {item.status.role}</p><code>{item.status.source.path} · {item.status.source.locator}</code></>}</details>
      <div className={styles.actions}><button onClick={()=>requestExit(()=>onNavigate(item.documentPath??item.source.path))}>Abrir documento de origen</button>{store.mode==='edit'&&Object.values(item.editable).some(Boolean)&&<button disabled={store.recoveryPending} onClick={()=>setEditing(!editing)}>Editar campos</button>}</div>
      {editing&&<div className={styles.form}><label>Campo<select value={field} onChange={e=>{const f=e.target.value as typeof field;setField(f);setValue(f==='title'?item.title:f==='description'?item.description??'':item.status?.raw??'');}}>{item.editable.title&&<option value="title">Título</option>}{item.editable.description&&<option value="description">Descripción</option>}{item.editable.status&&<option value="status">Estado</option>}</select></label><label>Nuevo valor{field==='status'?<select value={value} onChange={e=>setValue(e.target.value)}>{item.status?.allowed.map(s=><option key={s} value={s}>{s}</option>)}</select>:<textarea value={value} onChange={e=>setValue(e.target.value)}/>}</label><p className={styles.muted}>El identificador y el nombre de archivo no cambiarán.</p><button className="primary" disabled={store.recoveryPending} onClick={()=>plan(field,value)}>Revisar cambios</button></div>}
    </>}
    {exitAction&&<Dialog title="Hay una edición sin guardar" onClose={()=>setExitAction(null)}><p>Conserva el cambio de esta historia o descártalo antes de salir.</p><div className={styles.dialogFooter}><button onClick={()=>setExitAction(null)}>Seguir aquí</button><button onClick={()=>{const action=exitAction;setExitAction(null);action();}}>Descartar edición y continuar</button></div></Dialog>}
  </Dialog>;
}
