import {afterEach,beforeEach,describe,expect,it} from 'vitest';
import {createServer,type Server} from 'node:http';
import {mkdtemp,readFile,rm,stat,mkdir,writeFile,rmdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {serve} from '@hono/node-server';
import {createAdapter,JiraAdapter} from '../src/adapters';
import {ConnectorError,ProviderTransport} from '../src/transport';
import {createAtlassianApp} from '../src/service';
import {toAdf,markdownProjection} from '../../../packages/integrations/src';
import type {IntegrationPlan} from '../../../packages/integrations/src';
let server:Server,base:string,directory:string;
let hits:{method:string;path:string;body:any;authorization:string|undefined}[],version:number,title:string,description:string,applyMode:'ok'|'lost'|'partial',rateCount:number;
const origin='http://localhost:5173',launcher='test-launcher-capability-'.repeat(3),revision='a'.repeat(64);
const adf=(text:string)=>toAdf(markdownProjection(text));
beforeEach(async()=>{
  hits=[];version=1;title='Original';description='Original body';applyMode='ok';rateCount=0;directory=await mkdtemp(join(tmpdir(),'bmad-atlassian-test-'));
  server=createServer(async(req,res)=>{
    let raw='';for await(const chunk of req)raw+=chunk;let body:any;try{body=raw?JSON.parse(raw):undefined;}catch{}
    const url=new URL(req.url!,'http://localhost');hits.push({method:req.method!,path:url.pathname,body,authorization:req.headers.authorization});res.setHeader('Content-Type','application/json');
    const send=(value:unknown,status=200)=>{res.statusCode=status;res.end(JSON.stringify(value));};
    if(req.headers.authorization!=='Bearer provider-private'){send({error:'no'},401);return;}
    if(url.pathname.endsWith('/myself')||url.pathname.endsWith('/user/current')){send({accountId:'account-1',displayName:'Test account'});return;}
    if(url.pathname==='/rate'){if(rateCount++===0){res.setHeader('Retry-After','0');send({},429);}else send({ok:true});return;}
    if(url.pathname==='/redirect'){res.statusCode=302;res.setHeader('Location','http://127.0.0.1:1/leak');res.end();return;}
    if(url.pathname==='/large'){res.setHeader('Content-Length','3000000');res.end('x');return;}
    if(url.pathname==='/denied'){send({},403);return;}
    if(url.pathname==='/rest/api/3/project/search'){send({values:[{id:'10',key:'TEST',name:'Test project'}],isLast:true});return;}
    if(url.pathname==='/rest/api/3/search/jql'){send({issues:[{id:'100',key:'TEST-1',fields:{summary:title,project:{id:'10',key:'TEST'}}}],isLast:true});return;}
    if(url.pathname==='/rest/api/3/issue/100/transitions'){send({transitions:[{id:'31',name:'Start',to:{id:'2',name:'In Progress'},fields:{}},{id:'32',name:'Close',to:{id:'3',name:'Done'},fields:{resolution:{required:true}}}]});return;}
    if(url.pathname==='/rest/api/3/issue/100/changelog'){send({isLast:true,values:[{id:'1',created:'2026-01-01',author:{displayName:'Test'},items:[{field:'summary'}]}]});return;}
    if(url.pathname==='/rest/api/3/issue/100'){
      if(req.method==='PUT'){
        if(req.headers['if-match']!==String(version)){send({},412);return;}
        title=body.fields.summary??title;if(applyMode!=='partial')description=body.fields.description?markdownProjection(body.fields.description).markdown:description;version++;
        if(applyMode==='lost'){req.socket.destroy();return;}send({});return;
      }
      send({id:'100',key:'TEST-1',fields:{summary:title,description:adf(description),project:{id:'10',name:'Test project'},status:{id:'1',name:'Ready'},updated:String(version)}});return;
    }
    if(url.pathname==='/wiki/api/v2/spaces'){const cursor=url.searchParams.get('cursor');send(cursor?{results:[{id:'21',name:'Second',key:'TWO'}],_links:{}}:{results:[{id:'20',name:'Test space',key:'ONE'}],_links:{next:'/wiki/api/v2/spaces?cursor=next'}});return;}
    if(url.pathname==='/wiki/api/v2/pages'){send({results:[{id:'200',title:'Page',spaceId:'20',version:{number:1}}],_links:{}});return;}
    if(url.pathname==='/wiki/api/v2/pages/200/versions'){send({results:[{number:1,message:'Created',authorId:'account-1'}],_links:{}});return;}
    if(url.pathname==='/wiki/api/v2/pages/200'){send({id:'200',title:'Page',spaceId:'20',status:'current',version:{number:1},body:{atlas_doc_format:{value:JSON.stringify(adf('Page **body**'))}}});return;}
    send({},404);
  });
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+(server.address() as {port:number}).port;
});
afterEach(async()=>{await new Promise<void>(resolve=>server.close(()=>resolve()));await rm(directory,{recursive:true,force:true});});
function transport(extra={}){return new ProviderTransport({instance:base,authorization:'Bearer provider-private',allowHttpLoopbackForTests:true,timeoutMs:500,...extra});}
const jira=()=>createAdapter({provider:'jira',transport:transport()});
async function app(adapter=jira(),extra={}){return createAtlassianApp({adapter,origin,port:43121,launcherToken:launcher,journalDirectory:directory,...extra});}
async function request(app:Awaited<ReturnType<typeof createAtlassianApp>>,path:string,token=launcher,body?:unknown,method?:string){return app.request('http://127.0.0.1:43121'+path,{method:method??(body!==undefined?'POST':'GET'),headers:{Host:'127.0.0.1:43121',Origin:origin,Authorization:'Bearer '+token,...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body!==undefined?JSON.stringify(body):undefined});}
async function session(a:Awaited<ReturnType<typeof app>>){const result=await request(a,'/v1/session',launcher,{});expect(result.status).toBe(200);return (await result.json() as any).sessionToken as string;}
const planBody=(more={})=>({resourceId:'100',scopeId:'10',direction:'publish',fields:['title','description'],local:{path:'docs/story.md',revision,title:'Changed',text:'Changed body'},...more});
class AtomicTestAdapter extends JiraAdapter {
  constructor(){super({provider:'jira',transport:transport()});Object.assign(this.capabilities,{profile:'test-only-atomic-provider',remoteUpdate:true,concurrency:'atomic-test',blockedReasons:[]});}
  override async apply(plan:IntegrationPlan){await this.transport.request('/rest/api/3/issue/'+plan.resource.id,{method:'PUT',headers:{'If-Match':plan.resource.version},body:{fields:{summary:plan.local.title,description:plan.local.text}}});}
}
describe('verified production adapter capabilities and HTTP reads',()=>{
  it('reads authenticated identity, scopes, escaped search, issue, transitions and history',async()=>{const a=jira();expect(await a.identity()).toEqual({id:'account-1',displayName:'Test account'});expect((await a.scopes()).items[0].id).toBe('10');expect((await a.search('10','quoted " item')).items[0].id).toBe('100');const r=await a.read('100');expect(r.scopeId).toBe('10');expect(r.transitions?.[1].requiredFields).toEqual(['resolution']);expect(r.content.complete).toBe(true);expect((await a.history('100')).complete).toBe(true);expect(hits.find(h=>h.path.endsWith('/search/jql'))?.body.jql).toContain('\\"');expect(a.capabilities.remoteUpdate).toBe(false);});
  it('reads Confluence spaces with bounded safe pagination, page ADF, versions and unknown draft',async()=>{const a=createAdapter({provider:'confluence',transport:transport()});expect((await a.identity() as {id:string}).id).toBe('account-1');expect((await a.scopes()).items.map(s=>s.id)).toEqual(['20','21']);expect((await a.search('20','Page')).items[0].id).toBe('200');const r=await a.read('200');expect(r.version).toBe('1');expect(r.draft).toBe('unknown');expect(r.content.complete).toBe(true);expect((await a.history('200')).items[0].version).toBe('1');expect(a.capabilities.remoteUpdate).toBe(false);});
  it('exposes bounded read-only Data Center profiles',()=>{const j=createAdapter({provider:'jira',deployment:'data-center',transport:transport()});const c=createAdapter({provider:'confluence',deployment:'data-center',transport:transport()});expect(j.capabilities.fields).toEqual(['title','status']);expect(c.capabilities.fields).toEqual(['title']);expect(c.capabilities.remoteUpdate).toBe(false);});
  it('retries rate-limited reads once, never follows redirects or oversized bodies',async()=>{expect(await transport().request('/rate')).toEqual({ok:true});expect(rateCount).toBe(2);await expect(transport().request('/redirect')).rejects.toMatchObject({code:'provider_redirect'});await expect(transport().request('/large')).rejects.toMatchObject({code:'response_too_large'});await expect(transport().request('/denied')).rejects.toMatchObject({code:'provider_forbidden'});});
  it('rejects HTTP except explicit loopback tests and path traversal',async()=>{expect(()=>new ProviderTransport({instance:base,authorization:'x'})).toThrow();expect(()=>new ProviderTransport({instance:'http://example.com',authorization:'x',allowHttpLoopbackForTests:true})).toThrow();await expect(jira().read('../secrets')).rejects.toMatchObject({code:'invalid_id'});expect(hits.length).toBe(0);});
});
describe('independent loopback capability, sessions and plan authorization',()=>{
  it('verifies provider identity and never includes provider credentials',async()=>{const a=await app();const res=await request(a,'/v1/session',launcher,{});const text=await res.text();expect(text).toContain('Test account');expect(text).not.toContain('provider-private');expect((await request(a,'/v1/capabilities',launcher)).status).toBe(401);});
  it('rejects hostile origin/host, weak capabilities, wrong content type and private routes',async()=>{const a=await app();expect((await a.request('http://evil/v1/health',{headers:{Host:'evil'}})).status).toBe(403);expect((await a.request('http://127.0.0.1:43121/v1/session',{method:'POST',headers:{Host:'127.0.0.1:43121',Origin:'https://evil.example','Content-Type':'application/json'},body:'{}'})).status).toBe(403);expect((await request(a,'/v1/session','bad',{})).status).toBe(401);const token=await session(a);expect((await request(a,'/v1/files',token)).status).toBe(404);expect((await a.request('http://127.0.0.1:43121/v1/plans',{method:'POST',headers:{Host:'127.0.0.1:43121',Origin:origin,Authorization:'Bearer '+token},body:'{}'})).status).toBe(415);});
  it('returns reviewed payload hash but blocks production publish without sending an update',async()=>{const a=await app(),token=await session(a);const p=await request(a,'/v1/plans',token,planBody());const plan=await p.json() as any;expect(p.status).toBe(200);expect(plan.reviewedPayloadHash).toMatch(/^[a-f0-9]{64}$/);expect(plan.blockedReasons.join(' ')).toContain('atomic');expect((await request(a,'/v1/operations',token,{planId:plan.id})).status).toBe(409);expect(hits.filter(h=>h.method==='PUT')).toHaveLength(0);});
  it('imports only selected body and never writes local metadata through Node',async()=>{const a=await app(),token=await session(a);const p=await request(a,'/v1/plans',token,planBody({direction:'import',fields:['description'],local:{path:'docs/story.md',revision,title:'Changed',text:'---\nstatus: draft\n---\nChanged'}}));const plan=await p.json() as any;expect(plan.blockedReasons).toEqual([]);expect(plan.candidate.text).toBe('Original body');expect(plan.candidate.title).toBeUndefined();expect((await request(a,'/v1/operations',token,{planId:plan.id})).status).toBe(409);});
  it('requires exact scope, safe relative path and SHA256 snapshot revision',async()=>{const a=await app(),token=await session(a);expect((await request(a,'/v1/plans',token,planBody({scopeId:'other'}))).status).toBe(409);expect((await request(a,'/v1/plans',token,planBody({local:{path:'../secret',revision,text:'x'}}))).status).toBe(400);expect((await request(a,'/v1/plans',token,planBody({scopeId:undefined}))).status).toBe(400);});
  it('invalidates plans on disconnect and blocks wrong-session execute',async()=>{const a=await app(new AtomicTestAdapter()),token=await session(a),other=await session(a);const plan=await (await request(a,'/v1/plans',token,planBody())).json() as any;expect((await request(a,'/v1/operations',other,{planId:plan.id})).status).toBe(404);await request(a,'/v1/session',token,undefined,'DELETE');expect((await request(a,'/v1/operations',token,{planId:plan.id})).status).toBe(401);});
  it('prunes expired sessions before applying the session limit',async()=>{let now=Date.now();const a=await app(jira(),{now:()=>now,sessionTtlMs:100});for(let i=0;i<20;i++)await session(a);expect((await request(a,'/v1/session',launcher,{})).status).toBe(429);now+=101;expect((await request(a,'/v1/session',launcher,{})).status).toBe(200);});
  it('expires both sessions and reviewed plans without sending writes',async()=>{let now=Date.now();const a=await app(new AtomicTestAdapter(),{now:()=>now,sessionTtlMs:10000,planTtlMs:100});const token=await session(a);const plan=await (await request(a,'/v1/plans',token,planBody())).json() as any;now+=101;expect((await request(a,'/v1/operations',token,{planId:plan.id})).status).toBe(409);now+=10000;expect((await request(a,'/v1/scopes',token)).status).toBe(401);expect(hits.filter(h=>h.method==='PUT')).toHaveLength(0);});
  it('blocks partial body transport and transitions needing unreviewed fields',async()=>{const a=await app(),token=await session(a);const partial=await (await request(a,'/v1/plans',token,planBody({direction:'import',local:{path:'docs/story.md',revision,title:'Story',text:'![private](secret.png)'}}))).json() as any;expect(partial.transportLoss).toContain('image');expect(partial.blockedReasons.length).toBeGreaterThan(0);const transition=await (await request(a,'/v1/plans',token,planBody({fields:['status'],transitionId:'32',local:{path:'docs/story.md',revision,title:'Story',text:'Body',status:'Done'}}))).json() as any;expect(transition.blockedReasons.join(' ')).toContain('additional fields');});
  it('does not expose title or body outside the selected import fields',async()=>{const a=await app(),token=await session(a);const plan=await (await request(a,'/v1/plans',token,planBody({direction:'import',fields:['title']}))).json() as any;expect(plan.candidate.title).toBe('Original');expect(plan.candidate.text).toBeUndefined();expect(plan.candidate.status).toBeUndefined();});
  it('rejects client-controlled URLs, capabilities and JSON damage',async()=>{const a=await app(),token=await session(a);expect((await request(a,'/v1/session',launcher,{remoteUpdate:true})).status).toBe(400);expect((await request(a,'/v1/proxy?url=https://example.com',token)).status).toBe(404);const broken=await a.request('http://127.0.0.1:43121/v1/plans',{method:'POST',headers:{Host:'127.0.0.1:43121',Origin:origin,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:'{'});expect(broken.status).toBe(400);});
  it('serves the protocol through a real local HTTP listener',async()=>{let a:Awaited<ReturnType<typeof app>>;const local=serve({fetch:(request,env)=>a.fetch(request,env),hostname:'127.0.0.1',port:0});try{await new Promise(resolve=>local.once('listening',resolve));const port=(local.address() as {port:number}).port;a=await app(jira(),{port});const response=await fetch(`http://127.0.0.1:${port}/v1/health`);expect(response.status).toBe(200);expect(await response.json()).toMatchObject({provider:'jira',protocolVersion:1});}finally{await new Promise<void>(resolve=>local.close(()=>resolve()));}});
});
describe('test-only atomic adapter demonstrates write state machine without certifying providers',()=>{
  it('revalidates remote version before transmission',async()=>{const a=await app(new AtomicTestAdapter()),token=await session(a);const plan=await (await request(a,'/v1/plans',token,planBody())).json() as any;version++;expect((await request(a,'/v1/operations',token,{planId:plan.id})).status).toBe(409);expect(hits.filter(h=>h.method==='PUT')).toHaveLength(0);});
  it('handles an atomic precondition failure in the request gap without retrying',async()=>{class RacingAdapter extends AtomicTestAdapter {override async apply(plan:IntegrationPlan){version++;return super.apply(plan);}}const a=await app(new RacingAdapter()),token=await session(a);const plan=await (await request(a,'/v1/plans',token,planBody())).json() as any;const op=await (await request(a,'/v1/operations',token,{planId:plan.id})).json() as any;expect(op.status).toBe('rejected');expect(title).toBe('Original');expect(hits.filter(h=>h.method==='PUT')).toHaveLength(1);});
  it('persists journal before sending, verifies selected fields and deduplicates execution',async()=>{const a=await app(new AtomicTestAdapter()),token=await session(a);const plan=await (await request(a,'/v1/plans',token,planBody())).json() as any;const operation=await (await request(a,'/v1/operations',token,{planId:plan.id})).json() as any;expect(operation.status).toBe('verified');const duplicate=await (await request(a,'/v1/operations',token,{planId:plan.id})).json();expect(duplicate).toEqual(operation);expect(hits.filter(h=>h.method==='PUT')).toHaveLength(1);const journal=await readFile(join(directory,'operations.json'),'utf8');expect(journal).not.toContain('provider-private');if(process.platform!=='win32')expect((await stat(join(directory,'operations.json'))).mode&0o077).toBe(0);expect((await request(a,'/v1/operations/by-plan/'+plan.id,token)).status).toBe(200);});
  it('does not retry a lost response, blocks unresolved resource then reconciles by reading',async()=>{applyMode='lost';const a=await app(new AtomicTestAdapter()),token=await session(a);const plan=await (await request(a,'/v1/plans',token,planBody())).json() as any;const op=await (await request(a,'/v1/operations',token,{planId:plan.id})).json() as any;expect(op.status).toBe('uncertain');expect(hits.filter(h=>h.method==='PUT')).toHaveLength(1);const next=await (await request(a,'/v1/plans',token,planBody())).json() as any;expect((await request(a,'/v1/operations',token,{planId:next.id})).status).toBe(409);const reconciled=await (await request(a,'/v1/operations/'+op.id+'/reconcile',token,{})).json() as any;expect(reconciled.status).toBe('verified');expect(hits.filter(h=>h.method==='PUT')).toHaveLength(1);});
  it('discovers another connector journal and never overwrites it from an old snapshot',async()=>{const first=await app(new AtomicTestAdapter()),second=await app(new AtomicTestAdapter());const t1=await session(first),t2=await session(second);const p1=await (await request(first,'/v1/plans',t1,planBody())).json() as any;const one=await (await request(first,'/v1/operations',t1,{planId:p1.id})).json() as any;const p2=await (await request(second,'/v1/plans',t2,planBody({fields:['title'],local:{path:'docs/story.md',revision,title:'Second',text:'Changed body'}}))).json() as any;const two=await (await request(second,'/v1/operations',t2,{planId:p2.id})).json() as any;expect(two.status).toBe('verified');const records=await (await request(first,'/v1/operations',t1)).json() as any;expect(records.items.map((o:any)=>o.id)).toEqual(expect.arrayContaining([one.id,two.id]));expect(JSON.parse(await readFile(join(directory,'operations.json'),'utf8'))).toHaveLength(2);});
  it('does not steal a held or orphaned journal lock and exposes unfinished intent for reconciliation',async()=>{const a=await app(new AtomicTestAdapter()),token=await session(a);const plan=await (await request(a,'/v1/plans',token,planBody())).json() as any;await mkdir(join(directory,'.operation-lock'));expect((await request(a,'/v1/operations',token,{planId:plan.id})).status).toBe(409);expect(hits.filter(h=>h.method==='PUT')).toHaveLength(0);await rmdir(join(directory,'.operation-lock'));const op=await (await request(a,'/v1/operations',token,{planId:plan.id})).json() as any;const records=JSON.parse(await readFile(join(directory,'operations.json'),'utf8'));records[0].status='running';await writeFile(join(directory,'operations.json'),JSON.stringify(records),{mode:0o600});const restarted=await app(new AtomicTestAdapter()),next=await session(restarted);expect((await (await request(restarted,'/v1/operations/'+op.id,next)).json() as any).status).toBe('uncertain');const result=await (await request(restarted,'/v1/operations/'+op.id+'/reconcile',next,{})).json() as any;expect(result.status).toBe('verified');expect(hits.filter(h=>h.method==='PUT')).toHaveLength(1);});
  it('reports partial fields and retains recovery across restart',async()=>{applyMode='partial';const a=await app(new AtomicTestAdapter()),token=await session(a);const plan=await (await request(a,'/v1/plans',token,planBody())).json() as any;const op=await (await request(a,'/v1/operations',token,{planId:plan.id})).json() as any;expect(op.status).toBe('partial');const restarted=await app(new AtomicTestAdapter()),nextToken=await session(restarted);expect((await (await request(restarted,'/v1/operations/'+op.id,nextToken)).json() as any).status).toBe('partial');expect(hits.filter(h=>h.method==='PUT')).toHaveLength(1);});
});
